REPO_DIR=$(shell git rev-parse --show-toplevel)
PLUGIN_DIR=$(REPO_DIR)/plugins

init-dev:
	-@rm -rf .terraform*
	terraform init -plugin-dir $(PLUGIN_DIR)

init:
	-@rm -rf .terraform*
	terraform init

plan:
	terraform plan

apply:
	terraform apply -auto-approve

destroy:
	terraform destroy -auto-approve

clean:
	rm -rf .terraform* terraform*