// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Route_Map_Rule_Option

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type RouteMapRuleOptionResourceModel struct {
	AsNumber                   *[]AsPathExpressionResourceModel            `tfsdk:"as_number" json:"as_number,optional,omitempty" `
	AsPathType                 types.String                                `tfsdk:"as_path_type" json:"as_path_type,optional,omitempty" `
	CommunityNumber            *[]CommunityExpressionResourceModel         `tfsdk:"community_number" json:"community_number,optional,omitempty" `
	CommunityType              types.String                                `tfsdk:"community_type" json:"community_type,optional,omitempty" `
	DeleteCommunityRef         types.String                                `tfsdk:"delete_community_ref" json:"delete_community_ref,optional,omitempty" `
	ExtendedCommunityEntryType types.String                                `tfsdk:"extended_community_entry_type" json:"extended_community_entry_type,optional,omitempty" `
	ExtendedCommunityNumber    *[]ExtendedCommunityExpressionResourceModel `tfsdk:"extended_community_number" json:"extended_community_number,optional,omitempty" `
	ExtendedCommunityType      types.String                                `tfsdk:"extended_community_type" json:"extended_community_type,optional,omitempty" `
	Ipv4NextHop                *NextHopResourceModel                       `tfsdk:"ipv4_next_hop" json:"ipv4_next_hop,optional,omitempty" `
	Ipv6GlobalNextHop          *NextHopResourceModel                       `tfsdk:"ipv6_global_next_hop" json:"ipv6_global_next_hop,optional,omitempty" `
	Ipv6LocalNextHop           *NextHopResourceModel                       `tfsdk:"ipv6_local_next_hop" json:"ipv6_local_next_hop,optional,omitempty" `
	LocalPreference            types.Int64                                 `tfsdk:"local_preference" json:"local_preference,optional,omitempty" `
	Metric                     types.Int64                                 `tfsdk:"metric" json:"metric,optional,omitempty" `
	Weight                     types.Int64                                 `tfsdk:"weight" json:"weight,optional,omitempty" `
}
