// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Capabilities

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type CapabilitiesResourceModel struct {
	Sha2IkeHashLength   types.Int64 `tfsdk:"sha2_ike_hash_length" json:"sha2_ike_hash_length,optional,omitempty" `
	Sha2IpsecHashLength types.Int64 `tfsdk:"sha2_ipsec_hash_length" json:"sha2_ipsec_hash_length,optional,omitempty" `
}
