// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Server_Directories

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type ServerDirectoriesResourceModel struct {
	ArchiveMask types.Int64  `tfsdk:"archive_mask" json:"archive_mask,optional,omitempty" `
	OnlyArchive types.Bool   `tfsdk:"only_archive" json:"only_archive,optional,omitempty" `
	Server      types.String `tfsdk:"server" json:"server,optional,omitempty" `
}
