// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Log_Server

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type LogServerResourceModel struct {
	ID                                  types.String                                          `tfsdk:"id"`
	Address                             types.String                                          `tfsdk:"address" json:"address,optional,omitempty" `
	AdminDomain                         types.String                                          `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	BackupLogServer                     *[]SecondaryLogServerContainerForStorageResourceModel `tfsdk:"backup_log_server" json:"backup_log_server,optional,omitempty" `
	ChannelPort                         types.Int64                                           `tfsdk:"channel_port" json:"channel_port,optional,omitempty" `
	Comment                             types.String                                          `tfsdk:"comment" json:"comment,optional,omitempty" `
	ElasticsearchAuthenticationSettings *ElasticsearchAuthenticationSettingsResourceModel     `tfsdk:"elasticsearch_authentication_settings" json:"elasticsearch_authentication_settings,optional,omitempty" `
	ElasticsearchIndexingActive         types.Bool                                            `tfsdk:"elasticsearch_indexing_active" json:"elasticsearch_indexing_active,optional,omitempty" `
	Etag                                types.String                                          `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	ExternalPkiCertificateSettings      *CertificateSettingsResourceModel                     `tfsdk:"external_pki_certificate_settings" json:"external_pki_certificate_settings,optional,omitempty" `
	ForwardingTlsSettings               *TlsSettingsResourceModel                             `tfsdk:"forwarding_tls_settings" json:"forwarding_tls_settings,optional,omitempty" `
	Inactive                            types.Bool                                            `tfsdk:"inactive" json:"inactive,optional,omitempty" `
	Ipv6Address                         types.String                                          `tfsdk:"ipv6_address" json:"ipv6_address,optional,omitempty" `
	Key                                 types.Int64                                           `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                                customfield.NestedObjectList[ApiLinkResourceModel]    `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                                  customfield.Map[types.String]                         `tfsdk:"link" json:"-" `
	LocationRef                         types.String                                          `tfsdk:"location_ref" json:"location_ref,optional,omitempty" `
	Locked                              types.Bool                                            `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	LogDiskSpaceHandlingMode            types.String                                          `tfsdk:"log_disk_space_handling_mode" json:"log_disk_space_handling_mode,optional,omitempty" `
	Name                                types.String                                          `tfsdk:"name" json:"name,optional,omitempty" `
	NetflowCollector                    *[]NetflowCollectorResourceModel                      `tfsdk:"netflow_collector" json:"netflow_collector,optional,omitempty" `
	ReadOnly                            types.Bool                                            `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	Secondary                           *[]types.String                                       `tfsdk:"secondary" json:"secondary,optional,omitempty" `
	System                              types.Bool                                            `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey                           types.Int64                                           `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	ThirdPartyMonitoring                *ThirdPartyMonitoringResourceModel                    `tfsdk:"third_party_monitoring" json:"third_party_monitoring,optional,omitempty" `
	ToolsProfileRef                     types.String                                          `tfsdk:"tools_profile_ref" json:"tools_profile_ref,optional,omitempty" `
	Trashed                             types.Bool                                            `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
	Uiid                                types.String                                          `tfsdk:"uiid" json:"uiid,optional,omitempty" `
}

func (r *LogServerResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}
