// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: File_Reputation_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type FileReputationSettingsResourceModel struct {
	FileReputationContext types.String    `tfsdk:"file_reputation_context" json:"file_reputation_context,optional,omitempty" `
	HttpProxy             *[]types.String `tfsdk:"http_proxy" json:"http_proxy,optional,omitempty" `
}
