// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: ADSL_Physical_Interface

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type AdslPhysicalInterfaceResourceModel struct {
	AggregateMode                 types.String                                       `tfsdk:"aggregate_mode" json:"aggregate_mode,optional,omitempty" `
	ArpEntry                      *[]ArpEntryResourceModel                           `tfsdk:"arp_entry" json:"arp_entry,optional,omitempty" `
	Comment                       types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	CustomConfiguration           types.String                                       `tfsdk:"custom_configuration" json:"custom_configuration,optional,omitempty" `
	DhcpRelay                     *DhcpRelayResourceModel                            `tfsdk:"dhcp_relay" json:"dhcp_relay,optional,omitempty" `
	DhcpServerOnInterface         *DhcpServerSettingsResourceModel                   `tfsdk:"dhcp_server_on_interface" json:"dhcp_server_on_interface,optional,omitempty" `
	Dhcpv6Relay                   *DhcpRelayResourceModel                            `tfsdk:"dhcpv6_relay" json:"dhcpv6_relay,optional,omitempty" `
	DuplicateAddressDetection     types.Bool                                         `tfsdk:"duplicate_address_detection" json:"duplicate_address_detection,optional,omitempty" `
	IncludePrefixInfoOptionFlag   types.Bool                                         `tfsdk:"include_prefix_info_option_flag" json:"include_prefix_info_option_flag,optional,omitempty" `
	InterfaceId                   types.String                                       `tfsdk:"interface_id" json:"interface_id,optional,omitempty" `
	Interfaces                    *[]AbstractEngineInterfaceResourceModel            `tfsdk:"interfaces" json:"interfaces,optional,omitempty" `
	Key                           types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                          customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                            customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	LogModeration                 *[]LogModerationResourceModel                      `tfsdk:"log_moderation" json:"log_moderation,optional,omitempty" `
	MacPrefix                     types.String                                       `tfsdk:"mac_prefix" json:"mac_prefix,optional,omitempty" `
	ManagedAddressFlag            types.Bool                                         `tfsdk:"managed_address_flag" json:"managed_address_flag,optional,omitempty" `
	Mtu                           types.Int64                                        `tfsdk:"mtu" json:"mtu,optional,omitempty" `
	Name                          types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	OtherConfigurationFlag        types.Bool                                         `tfsdk:"other_configuration_flag" json:"other_configuration_flag,optional,omitempty" `
	OverrideEngineSettings        types.Bool                                         `tfsdk:"override_engine_settings" json:"override_engine_settings,optional,omitempty" `
	OverrideLogModerationSettings types.Bool                                         `tfsdk:"override_log_moderation_settings" json:"override_log_moderation_settings,optional,omitempty" `
	QosLimit                      types.Int64                                        `tfsdk:"qos_limit" json:"qos_limit,optional,omitempty" `
	QosMode                       types.String                                       `tfsdk:"qos_mode" json:"qos_mode,optional,omitempty" `
	QosPolicyRef                  types.String                                       `tfsdk:"qos_policy_ref" json:"qos_policy_ref,optional,omitempty" `
	RouterAdvertisement           types.Bool                                         `tfsdk:"router_advertisement" json:"router_advertisement,optional,omitempty" `
	SecondInterfaceId             types.String                                       `tfsdk:"second_interface_id" json:"second_interface_id,optional,omitempty" `
	SetAutonomousAddressFlag      types.Bool                                         `tfsdk:"set_autonomous_address_flag" json:"set_autonomous_address_flag,optional,omitempty" `
	SharedInterface               types.Bool                                         `tfsdk:"shared_interface" json:"shared_interface,optional,omitempty" `
	SynMaxBursts                  types.Int64                                        `tfsdk:"syn_max_bursts" json:"syn_max_bursts,optional,omitempty" `
	SynMode                       types.String                                       `tfsdk:"syn_mode" json:"syn_mode,optional,omitempty" `
	SynPerSecond                  types.Int64                                        `tfsdk:"syn_per_second" json:"syn_per_second,optional,omitempty" `
	VirtualResourceSettings       *[]VirtualResourceSettingsResourceModel            `tfsdk:"virtual_resource_settings" json:"virtual_resource_settings,optional,omitempty" `
	ZoneRef                       types.String                                       `tfsdk:"zone_ref" json:"zone_ref,optional,omitempty" `
}

func (r *AdslPhysicalInterfaceResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.InterfaceId.IsNull() || r.InterfaceId.IsUnknown() {
		return nil
	}
	return []string{r.InterfaceId.ValueString()}
}
