// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: VPN_Profile

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type VpnProfileResourceModel struct {
	ID                                     types.String                                       `tfsdk:"id"`
	AdminDomain                            types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	Capabilities                           *CapabilitiesResourceModel                         `tfsdk:"capabilities" json:"capabilities,optional,omitempty" `
	CnAuthenticationForMobileVpn           types.Bool                                         `tfsdk:"cn_authentication_for_mobile_vpn" json:"cn_authentication_for_mobile_vpn,optional,omitempty" `
	Comment                                types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	DisableAntiReplay                      types.Bool                                         `tfsdk:"disable_anti_replay" json:"disable_anti_replay,optional,omitempty" `
	DisablePathDiscovery                   types.Bool                                         `tfsdk:"disable_path_discovery" json:"disable_path_discovery,optional,omitempty" `
	Etag                                   types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	HybridAuthenticationForMobileVpn       types.Bool                                         `tfsdk:"hybrid_authentication_for_mobile_vpn" json:"hybrid_authentication_for_mobile_vpn,optional,omitempty" `
	IkeV2Ppk                               types.String                                       `tfsdk:"ike_v2_ppk" json:"ike_v2_ppk,optional,omitempty" `
	KeepAlive                              types.Bool                                         `tfsdk:"keep_alive" json:"keep_alive,optional,omitempty" `
	Key                                    types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                                   customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                                     customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked                                 types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	Name                                   types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	PresharedKeyAuthenticationForMobileVpn types.Bool                                         `tfsdk:"preshared_key_authentication_for_mobile_vpn" json:"preshared_key_authentication_for_mobile_vpn,optional,omitempty" `
	ReadOnly                               types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	SaLifeTime                             types.Int64                                        `tfsdk:"sa_life_time" json:"sa_life_time,optional,omitempty" `
	SaToAnyNetworkAllowed                  types.Bool                                         `tfsdk:"sa_to_any_network_allowed" json:"sa_to_any_network_allowed,optional,omitempty" `
	System                                 types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey                              types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Trashed                                types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
	TrustAllCas                            types.Bool                                         `tfsdk:"trust_all_cas" json:"trust_all_cas,optional,omitempty" `
	TrustedCertificateAuthority            *[]types.String                                    `tfsdk:"trusted_certificate_authority" json:"trusted_certificate_authority,optional,omitempty" `
	TunnelLifeTimeKbytes                   types.Int64                                        `tfsdk:"tunnel_life_time_kbytes" json:"tunnel_life_time_kbytes,optional,omitempty" `
	TunnelLifeTimeSeconds                  types.Int64                                        `tfsdk:"tunnel_life_time_seconds" json:"tunnel_life_time_seconds,optional,omitempty" `
}

func (r *VpnProfileResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}
