// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Authentication_Method_Container_for_Storage

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type AuthenticationMethodContainerForStorageResourceModel struct {
	AuthServerRef types.String `tfsdk:"auth_server_ref" json:"auth_server_ref,optional,omitempty" `
	Rank          types.Int64  `tfsdk:"rank" json:"rank,optional,omitempty" `
}
