// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Scheduled_Task

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type ScheduledTaskResourceModel struct {
	ID              types.String                                       `tfsdk:"id"`
	FromRef         types.String                                       `tfsdk:"from_ref"`
	Activated       types.Bool                                         `tfsdk:"activated" json:"activated,optional,omitempty" `
	ActivationDate  types.Int64                                        `tfsdk:"activation_date" json:"activation_date,optional,omitempty" `
	Comment         types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	DayMask         types.Int64                                        `tfsdk:"day_mask" json:"day_mask,optional,omitempty" `
	DayPeriod       types.String                                       `tfsdk:"day_period" json:"day_period,optional,omitempty" `
	Expired         types.Bool                                         `tfsdk:"expired" json:"expired,optional,omitempty" `
	FinalAction     types.String                                       `tfsdk:"final_action" json:"final_action,optional,omitempty" `
	Key             types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link            customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk              customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	MinutePeriod    types.String                                       `tfsdk:"minute_period" json:"minute_period,optional,omitempty" `
	Name            types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	RepeatUntilDate types.Int64                                        `tfsdk:"repeat_until_date" json:"repeat_until_date,optional,omitempty" `
}

func (r *ScheduledTaskResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}
