// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Source_Match_Part

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type SourceMatchPartResourceModel struct {
	Any            types.Bool      `tfsdk:"any" json:"any,optional,omitempty" `
	NetworkDetails *[]types.String `tfsdk:"resolved_src" json:"resolved_src,optional,omitempty" `
	None           types.Bool      `tfsdk:"none" json:"none,optional,omitempty" `
	Src            *[]types.String `tfsdk:"src" json:"src,optional,omitempty" `
}
