// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: BGP_Distance_Entry

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type BgpDistanceEntryResourceModel struct {
	Distance types.Int64  `tfsdk:"distance" json:"distance,optional,omitempty" `
	Subnet   types.String `tfsdk:"subnet" json:"subnet,optional,omitempty" `
}
