// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: User_Authentication_BBA

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type UserAuthenticationBbaResourceModel struct {
	AllInterfaces             types.Bool                            `tfsdk:"all_interfaces" json:"all_interfaces,optional,omitempty" `
	AuthenticationIdleTimeout types.Int64                           `tfsdk:"authentication_idle_timeout" json:"authentication_idle_timeout,optional,omitempty" `
	AuthenticationTimeout     types.Int64                           `tfsdk:"authentication_timeout" json:"authentication_timeout,optional,omitempty" `
	EnabledInterface          *[]EnabledInterfaceEntryResourceModel `tfsdk:"enabled_interface" json:"enabled_interface,optional,omitempty" `
	EnforceHttps              types.Bool                            `tfsdk:"enforce_https" json:"enforce_https,optional,omitempty" `
	HttpPort                  types.Int64                           `tfsdk:"http_port" json:"http_port,optional,omitempty" `
	HttpsPort                 types.Int64                           `tfsdk:"https_port" json:"https_port,optional,omitempty" `
	KeepAliveRate             types.Int64                           `tfsdk:"keep_alive_rate" json:"keep_alive_rate,optional,omitempty" `
	KeyLength                 types.Int64                           `tfsdk:"key_length" json:"key_length,optional,omitempty" `
	PageRef                   types.String                          `tfsdk:"page_ref" json:"page_ref,optional,omitempty" `
	SessionHandling           types.Bool                            `tfsdk:"session_handling" json:"session_handling,optional,omitempty" `
	SubjectName               types.String                          `tfsdk:"subject_name" json:"subject_name,optional,omitempty" `
	TlsProfile                types.String                          `tfsdk:"tls_profile" json:"tls_profile,optional,omitempty" `
	UseCertBba                types.Bool                            `tfsdk:"use_cert_bba" json:"use_cert_bba,optional,omitempty" `
}
