// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: TLS_Identity

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type TlsIdentityResourceModel struct {
	TlsField types.String `tfsdk:"tls_field" json:"tls_field,optional,omitempty" `
	TlsValue types.String `tfsdk:"tls_value" json:"tls_value,optional,omitempty" `
}
