// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: IPv6_Access_Rule

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type Ipv6AccessRuleResourceModel struct {
	ID                    types.String                                       `tfsdk:"id"`
	FromRef               types.String                                       `tfsdk:"from_ref"`
	Action                *FirewallRuleActionResourceModel                   `tfsdk:"action" json:"action,optional,omitempty" `
	AdminDomain           types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	AuthenticationOptions *UserAuthenticationMatchResourceModel              `tfsdk:"authentication_options" json:"authentication_options,optional,omitempty" `
	BackgroundColor       types.String                                       `tfsdk:"background_color" json:"background_color,optional,omitempty" `
	Comment               types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	Destinations          *DestinationMatchingPartResourceModel              `tfsdk:"destinations" json:"destinations,optional,omitempty" `
	Etag                  types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	Key                   types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                  customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                    customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked                types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	MatchVpnOptions       *MatchVpnOptionResourceModel                       `tfsdk:"match_vpn_options" json:"match_vpn_options,optional,omitempty" `
	Name                  types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	Options               *FirewallRuleOptionsResourceModel                  `tfsdk:"options" json:"options,optional,omitempty" `
	ParentInsertPoint     types.String                                       `tfsdk:"parent_insert_point" json:"parent_insert_point,optional,omitempty" fpro:"parent_insert_point"`
	ParentPolicy          types.String                                       `tfsdk:"parent_policy" json:"parent_policy,optional,omitempty" fpro:"parent_policy"`
	Rank                  types.Float64                                      `tfsdk:"rank" json:"rank,optional,omitempty" `
	ReadOnly              types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	RuleValidityTimes     *[]types.String                                    `tfsdk:"rule_validity_times" json:"rule_validity_times,optional,omitempty" `
	Services              *ServiceMatchPartResourceModel                     `tfsdk:"services" json:"services,optional,omitempty" `
	Sources               *SourceMatchPartResourceModel                      `tfsdk:"sources" json:"sources,optional,omitempty" `
	System                types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey             types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Tag                   types.String                                       `tfsdk:"tag" json:"tag,optional,omitempty" fpro:"tag"`
	Trashed               types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
	Type                  types.String                                       `tfsdk:"type" json:"type,optional,omitempty" `
}

func (r *Ipv6AccessRuleResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}
