// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: SAML_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type SamlSettingsResourceModel struct {
	SamlAcsUrl             types.String `tfsdk:"saml_acs_url" json:"saml_acs_url,optional,omitempty" `
	SamlMetadataFile       types.String `tfsdk:"saml_metadata_file" json:"saml_metadata_file,optional,omitempty" `
	SamlMethodRef          types.String `tfsdk:"saml_method_ref" json:"saml_method_ref,optional,omitempty" `
	SamlNameIdPolicyFormat types.String `tfsdk:"saml_name_id_policy_format" json:"saml_name_id_policy_format,optional,omitempty" `
	SamlServiceProviderId  types.String `tfsdk:"saml_service_provider_id" json:"saml_service_provider_id,optional,omitempty" `
	SamlSettingUsage       types.String `tfsdk:"saml_setting_usage" json:"saml_setting_usage,optional,omitempty" `
	SamlTlsCredentialsRef  types.String `tfsdk:"saml_tls_credentials_ref" json:"saml_tls_credentials_ref,optional,omitempty" `
	SamlUserAttribute      types.String `tfsdk:"saml_user_attribute" json:"saml_user_attribute,optional,omitempty" `
}
