// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Autonomous_System
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AutonomousSystemResource{}
var _ resource.ResourceWithImportState = &AutonomousSystemResource{}
var _ context.Context = context.Background()

// AutonomousSystemResource defines the resource implementation.
type AutonomousSystemResource struct {
	smcresource.ResourceBase[AutonomousSystemResourceModel]
}

// Schema defines the schema for the AutonomousSystem resource.
func (r *AutonomousSystemResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents the Autonomous System for Dynamic Routing Firewall functionality. The BGP Version is 4/4+. It includes the AS Number in decimal notation, which is used to identify the autonomous system in BGP routing.",
		Attributes:  GetAutonomousSystemSchemaAttributes(ctx),
		Blocks:      GetAutonomousSystemSchemaBlocks(ctx),
	} // schema

}

// NewAutonomousSystemResource creates a new instance of the AutonomousSystem resource.
func NewAutonomousSystemResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing AutonomousSystem resource")
	r := &AutonomousSystemResource{
		ResourceBase: smcresource.ResourceBase[AutonomousSystemResourceModel]{
			ResourceType:  "autonomous_system",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
