// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Float_Situation_Parameter_Value
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &FloatSituationParameterValueResource{}
var _ resource.ResourceWithImportState = &FloatSituationParameterValueResource{}
var _ context.Context = context.Background()

// FloatSituationParameterValueResource defines the resource implementation.
type FloatSituationParameterValueResource struct {
	smcresource.ResourceBase[FloatSituationParameterValueResourceModel]
}

// Schema defines the schema for the FloatSituationParameterValue resource.
func (r *FloatSituationParameterValueResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a float parameter value within a situation, allowing for the application of specific float values to the situation's parameters.",
		Attributes:  GetFloatSituationParameterValueSchemaAttributes(ctx),
		Blocks:      GetFloatSituationParameterValueSchemaBlocks(ctx),
	} // schema

}

// NewFloatSituationParameterValueResource creates a new instance of the FloatSituationParameterValue resource.
func NewFloatSituationParameterValueResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing FloatSituationParameterValue resource")
	r := &FloatSituationParameterValueResource{
		ResourceBase: smcresource.ResourceBase[FloatSituationParameterValueResourceModel]{
			ResourceType:  "float_situation_parameter_value",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
