// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Application_Usage_Tag
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ApplicationUsageTagResource{}
var _ resource.ResourceWithImportState = &ApplicationUsageTagResource{}
var _ context.Context = context.Background()

// ApplicationUsageTagResource defines the resource implementation.
type ApplicationUsageTagResource struct {
	smcresource.ResourceBase[ApplicationUsageTagResourceModel]
}

// Schema defines the schema for the ApplicationUsageTag resource.
func (r *ApplicationUsageTagResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an Application Usage Tag, which is used to categorize elements based on their application usage. It is a type of tag that can be applied to various elements in the system to indicate their application usage classification.",
		Attributes:  GetApplicationUsageTagSchemaAttributes(ctx),
		Blocks:      GetApplicationUsageTagSchemaBlocks(ctx),
	} // schema

}

// NewApplicationUsageTagResource creates a new instance of the ApplicationUsageTag resource.
func NewApplicationUsageTagResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ApplicationUsageTag resource")
	r := &ApplicationUsageTagResource{
		ResourceBase: smcresource.ResourceBase[ApplicationUsageTagResourceModel]{
			ResourceType:  "application_usage_tag",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
