// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: User_Alert_Check
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &UserAlertCheckResource{}
var _ resource.ResourceWithImportState = &UserAlertCheckResource{}
var _ context.Context = context.Background()

// UserAlertCheckResource defines the resource implementation.
type UserAlertCheckResource struct {
	smcresource.ResourceBase[UserAlertCheckResourceModel]
}

// Schema defines the schema for the UserAlertCheck resource.
func (r *UserAlertCheckResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a User Alert Check. It contains settings for the type of check, threshold values, filter, and associated alert.",
		Attributes:  GetUserAlertCheckSchemaAttributes(ctx),
		Blocks:      GetUserAlertCheckSchemaBlocks(ctx),
	} // schema

}

// NewUserAlertCheckResource creates a new instance of the UserAlertCheck resource.
func NewUserAlertCheckResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing UserAlertCheck resource")
	r := &UserAlertCheckResource{
		ResourceBase: smcresource.ResourceBase[UserAlertCheckResourceModel]{
			ResourceType:  "user_alert_check",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
