// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: L2_Interface_Policy
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &L2InterfacePolicyResource{}
var _ resource.ResourceWithImportState = &L2InterfacePolicyResource{}
var _ context.Context = context.Background()

// L2InterfacePolicyResource defines the resource implementation.
type L2InterfacePolicyResource struct {
	smcresource.ResourceBase[L2InterfacePolicyResourceModel]
}

// Schema defines the schema for the L2InterfacePolicy resource.
func (r *L2InterfacePolicyResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Layer 2 Interface Policy, which is used to define the action and inspection rules for L2FW Interface Engines.",
		Attributes:  GetL2InterfacePolicySchemaAttributes(ctx),
		Blocks:      GetL2InterfacePolicySchemaBlocks(ctx),
	} // schema

}

// NewL2InterfacePolicyResource creates a new instance of the L2InterfacePolicy resource.
func NewL2InterfacePolicyResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing L2InterfacePolicy resource")
	r := &L2InterfacePolicyResource{
		ResourceBase: smcresource.ResourceBase[L2InterfacePolicyResourceModel]{
			ResourceType:  "l2_interface_policy",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
