// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Inspection_Situation_Context
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &InspectionSituationContextResource{}
var _ resource.ResourceWithImportState = &InspectionSituationContextResource{}
var _ context.Context = context.Background()

// InspectionSituationContextResource defines the resource implementation.
type InspectionSituationContextResource struct {
	smcresource.ResourceBase[InspectionSituationContextResourceModel]
}

// Schema defines the schema for the InspectionSituationContext resource.
func (r *InspectionSituationContextResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Inspection Situation context. It can contain other groups or individual situation contexts.",
		Attributes:  GetInspectionSituationContextSchemaAttributes(ctx),
		Blocks:      GetInspectionSituationContextSchemaBlocks(ctx),
	} // schema

}

// NewInspectionSituationContextResource creates a new instance of the InspectionSituationContext resource.
func NewInspectionSituationContextResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing InspectionSituationContext resource")
	r := &InspectionSituationContextResource{
		ResourceBase: smcresource.ResourceBase[InspectionSituationContextResourceModel]{
			ResourceType:  "inspection_situation_context",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
