// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: SGInfo_Task
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &SginfoTaskResource{}
var _ resource.ResourceWithImportState = &SginfoTaskResource{}
var _ context.Context = context.Background()

// SginfoTaskResource defines the resource implementation.
type SginfoTaskResource struct {
	smcresource.ResourceBase[SginfoTaskResourceModel]
}

// Schema defines the schema for the SginfoTask resource.
func (r *SginfoTaskResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an SGInfo Task, which is used to collect system information from the engine. It is a type of task that can be scheduled and executed to gather system diagnostics and configuration details.",
		Attributes:  GetSginfoTaskSchemaAttributes(ctx),
		Blocks:      GetSginfoTaskSchemaBlocks(ctx),
	} // schema

}

// NewSginfoTaskResource creates a new instance of the SginfoTask resource.
func NewSginfoTaskResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing SginfoTask resource")
	r := &SginfoTaskResource{
		ResourceBase: smcresource.ResourceBase[SginfoTaskResourceModel]{
			ResourceType:  "sginfo_task",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
