// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Not_Browsed_LDAP_User_Group
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &NotBrowsedLdapUserGroupResource{}
var _ resource.ResourceWithImportState = &NotBrowsedLdapUserGroupResource{}
var _ context.Context = context.Background()

// NotBrowsedLdapUserGroupResource defines the resource implementation.
type NotBrowsedLdapUserGroupResource struct {
	smcresource.ResourceBase[NotBrowsedLdapUserGroupResourceModel]
}

// Schema defines the schema for the NotBrowsedLdapUserGroup resource.
func (r *NotBrowsedLdapUserGroupResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a User Group of a Domain where SMC does not connect to the directory server for browsing users and groups. It contains the ETag for versioning.",
		Attributes:  GetNotBrowsedLdapUserGroupSchemaAttributes(ctx),
		Blocks:      GetNotBrowsedLdapUserGroupSchemaBlocks(ctx),
	} // schema

}

// NewNotBrowsedLdapUserGroupResource creates a new instance of the NotBrowsedLdapUserGroup resource.
func NewNotBrowsedLdapUserGroupResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing NotBrowsedLdapUserGroup resource")
	r := &NotBrowsedLdapUserGroupResource{
		ResourceBase: smcresource.ResourceBase[NotBrowsedLdapUserGroupResourceModel]{
			ResourceType:  "ldap_user_group",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
