// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: URL_Category_Group_Tag
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &UrlCategoryGroupTagResource{}
var _ resource.ResourceWithImportState = &UrlCategoryGroupTagResource{}
var _ context.Context = context.Background()

// UrlCategoryGroupTagResource defines the resource implementation.
type UrlCategoryGroupTagResource struct {
	smcresource.ResourceBase[UrlCategoryGroupTagResourceModel]
}

// Schema defines the schema for the UrlCategoryGroupTag resource.
func (r *UrlCategoryGroupTagResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a URL Category Group Tag, which is used to categorize URL Categories based on their group classification. It is a type of tag that can be applied to various elements in the system to indicate their association with specific URL category groups.",
		Attributes:  GetUrlCategoryGroupTagSchemaAttributes(ctx),
		Blocks:      GetUrlCategoryGroupTagSchemaBlocks(ctx),
	} // schema

}

// NewUrlCategoryGroupTagResource creates a new instance of the UrlCategoryGroupTag resource.
func NewUrlCategoryGroupTagResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing UrlCategoryGroupTag resource")
	r := &UrlCategoryGroupTagResource{
		ResourceBase: smcresource.ResourceBase[UrlCategoryGroupTagResourceModel]{
			ResourceType:  "url_category_group",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
