// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Virtual_Resource
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VirtualResourceResource{}
var _ resource.ResourceWithImportState = &VirtualResourceResource{}
var _ context.Context = context.Background()

// VirtualResourceResource defines the resource implementation.
type VirtualResourceResource struct {
	smcresource.ResourceBase[VirtualResourceResourceModel]
}

// Schema defines the schema for the VirtualResource resource.
func (r *VirtualResourceResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a set of resources on the Master NGFW Engine that are allocated to each Virtual NGFW Engine. It includes properties such as ID, domain allocation, and resource limits.",
		Attributes:  GetVirtualResourceSchemaAttributes(ctx),
		Blocks:      GetVirtualResourceSchemaBlocks(ctx),
	} // schema

}

// NewVirtualResourceResource creates a new instance of the VirtualResource resource.
func NewVirtualResourceResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VirtualResource resource")
	r := &VirtualResourceResource{
		ResourceBase: smcresource.ResourceBase[VirtualResourceResourceModel]{
			ResourceType:  "virtual_resource",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
