// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Alias
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AliasResource{}
var _ resource.ResourceWithImportState = &AliasResource{}
var _ context.Context = context.Background()

// AliasResource defines the resource implementation.
type AliasResource struct {
	smcresource.ResourceBase[AliasResourceModel]
}

// Schema defines the schema for the Alias resource.
func (r *AliasResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an Alias, which is used to represent other network elements in configurations. It allows for flexible configuration by defining default values and alias values that can be used in policies.",
		Attributes:  GetAliasSchemaAttributes(ctx),
		Blocks:      GetAliasSchemaBlocks(ctx),
	} // schema

}

// NewAliasResource creates a new instance of the Alias resource.
func NewAliasResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing Alias resource")
	r := &AliasResource{
		ResourceBase: smcresource.ResourceBase[AliasResourceModel]{
			ResourceType:  "alias",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
