// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Gateway_Tunnel
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &GatewayTunnelResource{}
var _ resource.ResourceWithImportState = &GatewayTunnelResource{}
var _ context.Context = context.Background()

// GatewayTunnelResource defines the resource implementation.
type GatewayTunnelResource struct {
	smcresource.ResourceBase[GatewayTunnelResourceModel]
}

// Schema defines the schema for the GatewayTunnel resource.
func (r *GatewayTunnelResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a gateway tunnel, which is used to manage the logical tunnels between gateway nodes in the VPN topology.",
		Attributes:  GetGatewayTunnelSchemaAttributes(ctx),
		Blocks:      GetGatewayTunnelSchemaBlocks(ctx),
	} // schema

}

// NewGatewayTunnelResource creates a new instance of the GatewayTunnel resource.
func NewGatewayTunnelResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing GatewayTunnel resource")
	r := &GatewayTunnelResource{
		ResourceBase: smcresource.ResourceBase[GatewayTunnelResourceModel]{
			ResourceType:  "gateway_tunnel",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
