// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Sensor
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &SingleSensorResource{}
var _ resource.ResourceWithImportState = &SingleSensorResource{}
var _ context.Context = context.Background()

// SingleSensorResource defines the resource implementation.
type SingleSensorResource struct {
	smcresource.ResourceBase[SingleSensorResourceModel]
}

// Schema defines the schema for the SingleSensor resource.
func (r *SingleSensorResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Single IPS device in the Stonesoft Management Center, which is a single IPS engine. It includes attributes for virtual defragmentation and connection limits.",
		Attributes:  GetSingleSensorSchemaAttributes(ctx),
		Blocks:      GetSingleSensorSchemaBlocks(ctx),
	} // schema

}

// NewSingleSensorResource creates a new instance of the SingleSensor resource.
func NewSingleSensorResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing SingleSensor resource")
	r := &SingleSensorResource{
		ResourceBase: smcresource.ResourceBase[SingleSensorResourceModel]{
			ResourceType:  "single_ips",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
