// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Inspection_Template_Policy
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &InspectionTemplatePolicyResource{}
var _ resource.ResourceWithImportState = &InspectionTemplatePolicyResource{}
var _ context.Context = context.Background()

// InspectionTemplatePolicyResource defines the resource implementation.
type InspectionTemplatePolicyResource struct {
	smcresource.ResourceBase[InspectionTemplatePolicyResourceModel]
}

// Schema defines the schema for the InspectionTemplatePolicy resource.
func (r *InspectionTemplatePolicyResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an Inspection Template Policy, which is used to define a set of rules and insert points that can be inherited by other policies or template policies.",
		Attributes:  GetInspectionTemplatePolicySchemaAttributes(ctx),
		Blocks:      GetInspectionTemplatePolicySchemaBlocks(ctx),
	} // schema

}

// NewInspectionTemplatePolicyResource creates a new instance of the InspectionTemplatePolicy resource.
func NewInspectionTemplatePolicyResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing InspectionTemplatePolicy resource")
	r := &InspectionTemplatePolicyResource{
		ResourceBase: smcresource.ResourceBase[InspectionTemplatePolicyResourceModel]{
			ResourceType:  "inspection_template_policy",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
