// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Validm_Vpn_DHCP_Address_Pools_Alias
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ValidmVpnDhcpAddressPoolsAliasResource{}
var _ resource.ResourceWithImportState = &ValidmVpnDhcpAddressPoolsAliasResource{}
var _ context.Context = context.Background()

// ValidmVpnDhcpAddressPoolsAliasResource defines the resource implementation.
type ValidmVpnDhcpAddressPoolsAliasResource struct {
	smcresource.ResourceBase[ValidmVpnDhcpAddressPoolsAliasResourceModel]
}

// Schema defines the schema for the ValidmVpnDhcpAddressPoolsAlias resource.
func (r *ValidmVpnDhcpAddressPoolsAliasResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents the System alias for '$$ Valid DHCP Address Pools for IPsec VPN clients', which is used to substitute address pools defined in the Internal Security Gateway properties for assigning virtual IP addresses to IPsec VPN clients.",
		Attributes:  GetValidmVpnDhcpAddressPoolsAliasSchemaAttributes(ctx),
		Blocks:      GetValidmVpnDhcpAddressPoolsAliasSchemaBlocks(ctx),
	} // schema

}

// NewValidmVpnDhcpAddressPoolsAliasResource creates a new instance of the ValidmVpnDhcpAddressPoolsAlias resource.
func NewValidmVpnDhcpAddressPoolsAliasResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ValidmVpnDhcpAddressPoolsAlias resource")
	r := &ValidmVpnDhcpAddressPoolsAliasResource{
		ResourceBase: smcresource.ResourceBase[ValidmVpnDhcpAddressPoolsAliasResourceModel]{
			ResourceType:  "valid_vpn_dhcp_address_pools_alias",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
