// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Broker_Domain_Config_File
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &BrokerDomainConfigFileResource{}
var _ resource.ResourceWithImportState = &BrokerDomainConfigFileResource{}
var _ context.Context = context.Background()

// BrokerDomainConfigFileResource defines the resource implementation.
type BrokerDomainConfigFileResource struct {
	smcresource.ResourceBase[BrokerDomainConfigFileResourceModel]
}

// Schema defines the schema for the BrokerDomainConfigFile resource.
func (r *BrokerDomainConfigFileResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This is a configuration file for the VPN Broker Domain. It contains settings and configurations specific to the broker domain, used for managing VPN connections and policies.",
		Attributes:  GetBrokerDomainConfigFileSchemaAttributes(ctx),
		Blocks:      GetBrokerDomainConfigFileSchemaBlocks(ctx),
	} // schema

}

// NewBrokerDomainConfigFileResource creates a new instance of the BrokerDomainConfigFile resource.
func NewBrokerDomainConfigFileResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing BrokerDomainConfigFile resource")
	r := &BrokerDomainConfigFileResource{
		ResourceBase: smcresource.ResourceBase[BrokerDomainConfigFileResourceModel]{
			ResourceType:  "broker_config_file",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
