// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: IPv4_NAT_Rule
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &Ipv4NatRuleResource{}
var _ resource.ResourceWithImportState = &Ipv4NatRuleResource{}
var _ context.Context = context.Background()

// Ipv4NatRuleResource defines the resource implementation.
type Ipv4NatRuleResource struct {
	smcresource.ResourceBase[Ipv4NatRuleResourceModel]
}

// Schema defines the schema for the Ipv4NatRule resource.
func (r *Ipv4NatRuleResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an IPv4 NAT (Network Address Translation) Rule. It defines how one type of IPv4 connection is natted, enhancing security and enabling communication for hosts with non-routable addresses.",
		Attributes:  GetIpv4NatRuleSchemaAttributes(ctx),
		Blocks:      GetIpv4NatRuleSchemaBlocks(ctx),
	} // schema

}

// NewIpv4NatRuleResource creates a new instance of the Ipv4NatRule resource.
func NewIpv4NatRuleResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing Ipv4NatRule resource")
	r := &Ipv4NatRuleResource{
		ResourceBase: smcresource.ResourceBase[Ipv4NatRuleResourceModel]{
			ResourceType:  "fw_ipv4_nat_rule",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}

// special case for rank attribute
func (r *Ipv4NatRuleResource) getCreateRequestParams(_ context.Context, data *Ipv4NatRuleResourceModel) (map[string]string, error) {
	if !data.Rank.IsNull() && !data.Rank.IsUnknown() {
		queryParams := map[string]string{
			"keep_specified_rank": "true",
		}
		return queryParams, nil
	}
	return nil, nil
}
