// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Application_Situation_Context
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ApplicationSituationContextResource{}
var _ resource.ResourceWithImportState = &ApplicationSituationContextResource{}
var _ context.Context = context.Background()

// ApplicationSituationContextResource defines the resource implementation.
type ApplicationSituationContextResource struct {
	smcresource.ResourceBase[ApplicationSituationContextResourceModel]
}

// Schema defines the schema for the ApplicationSituationContext resource.
func (r *ApplicationSituationContextResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an Application Situation context. It can contain other groups or individual situation contexts.",
		Attributes:  GetApplicationSituationContextSchemaAttributes(ctx),
		Blocks:      GetApplicationSituationContextSchemaBlocks(ctx),
	} // schema

}

// NewApplicationSituationContextResource creates a new instance of the ApplicationSituationContext resource.
func NewApplicationSituationContextResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ApplicationSituationContext resource")
	r := &ApplicationSituationContextResource{
		ResourceBase: smcresource.ResourceBase[ApplicationSituationContextResourceModel]{
			ResourceType:  "application_situation_context",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
