// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: ICMP_Service_Group
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &IcmpServiceGroupResource{}
var _ resource.ResourceWithImportState = &IcmpServiceGroupResource{}
var _ context.Context = context.Background()

// IcmpServiceGroupResource defines the resource implementation.
type IcmpServiceGroupResource struct {
	smcresource.ResourceBase[IcmpServiceGroupResourceModel]
}

// Schema defines the schema for the IcmpServiceGroup resource.
func (r *IcmpServiceGroupResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an ICMP Service Group, which is used to group a list of ICMP Services. It can contain both individual ICMP Services and other Service Groups.",
		Attributes:  GetIcmpServiceGroupSchemaAttributes(ctx),
		Blocks:      GetIcmpServiceGroupSchemaBlocks(ctx),
	} // schema

}

// NewIcmpServiceGroupResource creates a new instance of the IcmpServiceGroup resource.
func NewIcmpServiceGroupResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing IcmpServiceGroup resource")
	r := &IcmpServiceGroupResource{
		ResourceBase: smcresource.ResourceBase[IcmpServiceGroupResourceModel]{
			ResourceType:  "icmp_service_group",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
