// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Connection_Type
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ConnectionTypeResource{}
var _ resource.ResourceWithImportState = &ConnectionTypeResource{}
var _ context.Context = context.Background()

// ConnectionTypeResource defines the resource implementation.
type ConnectionTypeResource struct {
	smcresource.ResourceBase[ConnectionTypeResourceModel]
}

// Schema defines the schema for the ConnectionType resource.
func (r *ConnectionTypeResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a connection type used in endpoints, which defines the connectivity group, mode, and link type for VPN connections.",
		Attributes:  GetConnectionTypeSchemaAttributes(ctx),
		Blocks:      GetConnectionTypeSchemaBlocks(ctx),
	} // schema

}

// NewConnectionTypeResource creates a new instance of the ConnectionType resource.
func NewConnectionTypeResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ConnectionType resource")
	r := &ConnectionTypeResource{
		ResourceBase: smcresource.ResourceBase[ConnectionTypeResourceModel]{
			ResourceType:  "connection_type",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
