// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: External_LDAP_User_Group
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ExternalLdapUserGroupResource{}
var _ resource.ResourceWithImportState = &ExternalLdapUserGroupResource{}
var _ context.Context = context.Background()

// ExternalLdapUserGroupResource defines the resource implementation.
type ExternalLdapUserGroupResource struct {
	smcresource.ResourceBase[ExternalLdapUserGroupResourceModel]
}

// Schema defines the schema for the ExternalLdapUserGroup resource.
func (r *ExternalLdapUserGroupResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a group of external LDAP Users defined on the external LDAP server. It allows browsing and invalidating user entries.",
		Attributes:  GetExternalLdapUserGroupSchemaAttributes(ctx),
		Blocks:      GetExternalLdapUserGroupSchemaBlocks(ctx),
	} // schema

}

// NewExternalLdapUserGroupResource creates a new instance of the ExternalLdapUserGroup resource.
func NewExternalLdapUserGroupResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ExternalLdapUserGroup resource")
	r := &ExternalLdapUserGroupResource{
		ResourceBase: smcresource.ResourceBase[ExternalLdapUserGroupResourceModel]{
			ResourceType:  "external_ldap_user_group",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
