// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Reference_Situation_Parameter_Value
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ReferenceSituationParameterValueResource{}
var _ resource.ResourceWithImportState = &ReferenceSituationParameterValueResource{}
var _ context.Context = context.Background()

// ReferenceSituationParameterValueResource defines the resource implementation.
type ReferenceSituationParameterValueResource struct {
	smcresource.ResourceBase[ReferenceSituationParameterValueResourceModel]
}

// Schema defines the schema for the ReferenceSituationParameterValue resource.
func (r *ReferenceSituationParameterValueResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a reference parameter value within a situation, allowing for the application of specific references to the situation's parameters.",
		Attributes:  GetReferenceSituationParameterValueSchemaAttributes(ctx),
		Blocks:      GetReferenceSituationParameterValueSchemaBlocks(ctx),
	} // schema

}

// NewReferenceSituationParameterValueResource creates a new instance of the ReferenceSituationParameterValue resource.
func NewReferenceSituationParameterValueResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ReferenceSituationParameterValue resource")
	r := &ReferenceSituationParameterValueResource{
		ResourceBase: smcresource.ResourceBase[ReferenceSituationParameterValueResourceModel]{
			ResourceType:  "reference_situation_parameter_value",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
