// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: NTP_Server
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &NtpServerResource{}
var _ resource.ResourceWithImportState = &NtpServerResource{}
var _ context.Context = context.Background()

// NtpServerResource defines the resource implementation.
type NtpServerResource struct {
	smcresource.ResourceBase[NtpServerResourceModel]
}

// Schema defines the schema for the NtpServer resource.
func (r *NtpServerResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an NTP server, which is used to synchronize the time across network devices. It includes attributes for host name, authentication key type, and optional authentication key ID and key.",
		Attributes:  GetNtpServerSchemaAttributes(ctx),
		Blocks:      GetNtpServerSchemaBlocks(ctx),
	} // schema

}

// NewNtpServerResource creates a new instance of the NtpServer resource.
func NewNtpServerResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing NtpServer resource")
	r := &NtpServerResource{
		ResourceBase: smcresource.ResourceBase[NtpServerResourceModel]{
			ResourceType:  "ntp",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
