// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: L2_Interface_Template_Policy
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &L2InterfaceTemplatePolicyResource{}
var _ resource.ResourceWithImportState = &L2InterfaceTemplatePolicyResource{}
var _ context.Context = context.Background()

// L2InterfaceTemplatePolicyResource defines the resource implementation.
type L2InterfaceTemplatePolicyResource struct {
	smcresource.ResourceBase[L2InterfaceTemplatePolicyResourceModel]
}

// Schema defines the schema for the L2InterfaceTemplatePolicy resource.
func (r *L2InterfaceTemplatePolicyResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Layer 2 Interface Template Policy, which is used to define a set of rules and insert points that can be inherited by other policies or template policies.",
		Attributes:  GetL2InterfaceTemplatePolicySchemaAttributes(ctx),
		Blocks:      GetL2InterfaceTemplatePolicySchemaBlocks(ctx),
	} // schema

}

// NewL2InterfaceTemplatePolicyResource creates a new instance of the L2InterfaceTemplatePolicy resource.
func NewL2InterfaceTemplatePolicyResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing L2InterfaceTemplatePolicy resource")
	r := &L2InterfaceTemplatePolicyResource{
		ResourceBase: smcresource.ResourceBase[L2InterfaceTemplatePolicyResourceModel]{
			ResourceType:  "l2_interface_template_policy",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
