// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Correlation_Situation
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &CorrelationSituationResource{}
var _ resource.ResourceWithImportState = &CorrelationSituationResource{}
var _ context.Context = context.Background()

// CorrelationSituationResource defines the resource implementation.
type CorrelationSituationResource struct {
	smcresource.ResourceBase[CorrelationSituationResourceModel]
}

// Schema defines the schema for the CorrelationSituation resource.
func (r *CorrelationSituationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Correlation Situation, which is used to group together event data to find patterns in that data.",
		Attributes:  GetCorrelationSituationSchemaAttributes(ctx),
		Blocks:      GetCorrelationSituationSchemaBlocks(ctx),
	} // schema

}

// NewCorrelationSituationResource creates a new instance of the CorrelationSituation resource.
func NewCorrelationSituationResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing CorrelationSituation resource")
	r := &CorrelationSituationResource{
		ResourceBase: smcresource.ResourceBase[CorrelationSituationResourceModel]{
			ResourceType:  "correlation_situation",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
