// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetRouteMapMatchingConditionSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{"access_list_ref": schema.StringAttribute{
		Optional:    true,
		Description: "This represents an abstract access list used in dynamic routing. It contains a list of access list entries that define the rules for routing decisions.",
	},
		"external_bgp_peer_address_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents the External BGP Peer for Dynamic Routing Firewall functionality. It is used to configure external BGP peers in the firewall's dynamic routing capabilities.",
		},
		"fwcluster_peer_address_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a group of devices, or nodes, that share a given work load. You can cluster Firewalls to share the load and provide redundancy, allowing, for example, scheduled maintenance that takes one node out of service without interrupting services to the users.",
		},
		"metric": schema.Int64Attribute{
			Optional:    true,
			Description: "The Metric value used for matching routes in the Route Map Rule.",
		},
		"next_hop_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents an abstract access list used in dynamic routing. It contains a list of access list entries that define the rules for routing decisions.",
		},
		"rank": schema.Int64Attribute{
			Optional:    true,
			Description: "The rank of this matching condition, which determines its priority in the Route Map Rule.",
		},
		"type": schema.StringAttribute{
			Optional:    true,
			Description: "The type of matching condition, which can be 'element', 'next_hop', 'metric', or 'peer_address'.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getRouteMapMatchingConditionSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetRouteMapMatchingConditionSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getRouteMapMatchingConditionSchemaBlocksInternal(ctx)
}

func getRouteMapMatchingConditionSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{}
}
