// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetDhcpRelaySchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{"element": schema.ListAttribute{
		Optional:    true,
		Description: "URI of the DHCP Server.",
		ElementType: types.StringType,
	},
		"enabled": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the DHCP Relay is enabled on this interface.",
		},
		"max_packet_size": schema.Int64Attribute{
			Optional:    true,
			Description: "The maximum packet size for DHCP Relay, which is required if DHCP Relay is enabled.",
		},
		"trusted_circuit": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the DHCP Relay is configured for a trusted circuit.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getDhcpRelaySchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetDhcpRelaySchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getDhcpRelaySchemaBlocksInternal(ctx)
}

func getDhcpRelaySchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{}
}
