// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetUrlListApplicationSituationSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Description: "this attribute is the identifier of terraform resource",
		}, "admin_domain": schema.StringAttribute{
			Computed:    true,
			Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
		},
		"attacker": schema.StringAttribute{
			Optional:    true,
			Description: "The attacker involved in the situation, which can be 'none', 'packet_destination', 'connection_source', or 'connection_destination'. By default, it is set to 'none'.",
		},
		"comment": schema.StringAttribute{
			Optional:    true,
			Description: "An optional comment for the element. This field is not required.",
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Description: "A long description of the situation, providing detailed information about its nature and implications.",
		},
		"display_name": schema.StringAttribute{
			Optional:    true,
			Description: "The internal display name of the situation, which is used for identification purposes within the system.",
		},
		"etag": schema.StringAttribute{
			Computed:    true,
			Description: "The ETag of the element, used for versioning. This field is not required.",
		},
		"hidden": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the situation is hidden from the user interface. If true, it is not displayed to users.",
		},
		"identifiable_with_tls_match": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the application can be identified by a TLS match.",
		},
		"key": schema.Int64Attribute{
			Computed:    true,
			Description: "The unique identifier for the element. This field is required for updates but not for creation.",
		},
		"link": schema.MapAttribute{
			Computed:    true,
			Description: "provides additional actions or resources.",
			ElementType: types.StringType,
			CustomType:  customfield.NewMapType[types.String](ctx),
		},
		"locked": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is locked. This field is not required.",
		},
		"mime_type": schema.StringAttribute{
			Optional:    true,
			Description: "The MIME type associated with the situation, which indicates the type of content or data involved in the situation.",
		},
		"name": schema.StringAttribute{
			Optional:    true,
			Description: "Name of the object.",
		},
		"parameter_values": schema.ListAttribute{
			Optional:    true,
			Description: "URI of the associated parameter value.",
			ElementType: types.StringType,
		},
		"parent_application_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a situation related to an application, including its parent application, protocol agent, TLS match, and associated ports.",
		},
		"protocol_agent_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a Protocol Agent. It is a process on the engines that assists the engine in handling a particular Protocol. Protocol Agents ensure that related connections for a service are properly grouped and evaluated by the engine, as well as assisting the engine with content filtering or network address translation tasks.",
		},
		"read_only": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is read-only. This field is not required.",
		},
		"sanity_check": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether a sanity check is performed on the situation. If true, it ensures that the situation meets certain criteria before being processed.",
		},
		"severity": schema.Int64Attribute{
			Optional:    true,
			Description: "The severity of the situation, ranging from 1 (Info) to 10 (Critical). By default, it is set to 1 (Info).",
		},
		"situation_context_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a context for a situation, including its minimum and maximum supported engine versions and associated parameters.",
		},
		"ssm_mib": schema.StringAttribute{
			Optional:    true,
			Description: "The Sidewinder MIB (Management Information Base) associated with the situation, which is used for monitoring and management purposes.",
		},
		"system": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is a System element. This field is not required.",
		},
		"system_key": schema.Int64Attribute{
			Computed:    true,
			Description: "The system key of the System element. This field is not required.",
		},
		"tls_match_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a TLS Match Situation, which defines matching criteria for the use of the TLS protocol in traffic, allowing you to prevent specified traffic from being decrypted.",
		},
		"trashed": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is trashed. This field is not required.",
		},
		"upcoming_event_enabled": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the situation is enabled for upcoming events. If true, it means that the situation will be considered for upcoming event processing.",
		},
		"upcoming_event_threshold": schema.Int64Attribute{
			Optional:    true,
			Description: "The threshold in days for upcoming events related to the situation. If the situation is enabled for upcoming events, this value indicates how many days in advance the event should be considered.",
		},
		"url_entry": schema.ListAttribute{
			Optional:    true,
			Description: "The URLs.",
			ElementType: types.StringType,
		},
		"victim": schema.StringAttribute{
			Optional:    true,
			Description: "The victim involved in the situation, which can be 'none', 'packet_destination', 'connection_source', or 'connection_destination'. By default, it is set to 'none'.",
		},
		"vulnerability_references": schema.ListAttribute{
			Optional:    true,
			Description: "A set of references to vulnerabilities associated with the situation, providing additional context and information about potential security issues.",
			ElementType: types.StringType,
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getUrlListApplicationSituationSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetUrlListApplicationSituationSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getUrlListApplicationSituationSchemaBlocksInternal(ctx)
}

func getUrlListApplicationSituationSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{
		"application_port": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetApplicationPortSchemaAttributes(ctx),
				Blocks:     GetApplicationPortSchemaBlocks(ctx),
			},
		},
		"pa_values": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetAbstractPaParameterValueWrapperSchemaAttributes(ctx),
				Blocks:     GetAbstractPaParameterValueWrapperSchemaBlocks(ctx),
			},
		},
	}
}
