// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetOspfv2InterfaceSettingsSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Description: "this attribute is the identifier of terraform resource",
		}, "admin_domain": schema.StringAttribute{
			Computed:    true,
			Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
		},
		"authentication_type": schema.StringAttribute{
			Optional:    true,
			Description: "The type of OSPF authentication used on the interface.",
		},
		"comment": schema.StringAttribute{
			Optional:    true,
			Description: "An optional comment for the element. This field is not required.",
		},
		"dead_interval": schema.Int64Attribute{
			Optional:    true,
			Description: "The Dead interval in seconds for OSPF, which is the time after which a neighbor is considered down if no Hello packets are received.",
		},
		"dead_multiplier": schema.Int64Attribute{
			Optional:    true,
			Description: "The multiplier for the Hello interval used to calculate the Dead interval when using 'minimal' Hello interval type.",
		},
		"etag": schema.StringAttribute{
			Computed:    true,
			Description: "The ETag of the element, used for versioning. This field is not required.",
		},
		"hello_interval": schema.Int64Attribute{
			Optional:    true,
			Description: "The Hello interval in seconds for OSPF, which is the time between Hello packets sent on the interface.",
		},
		"hello_interval_type": schema.StringAttribute{
			Optional:    true,
			Description: "The type of Hello interval used in OSPF, which can be 'normal', 'minimal', or 'fast_hello'.",
		},
		"interface_cost": schema.Int64Attribute{
			Optional:    true,
			Description: "The cost of the OSPF interface, which affects the routing decisions made by OSPF.",
		},
		"key": schema.Int64Attribute{
			Computed:    true,
			Description: "The unique identifier for the element. This field is required for updates but not for creation.",
		},
		"key_chain_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents an abstract OSPF Key Chain used as a Dynamic Routing element. It contains settings related to OSPF key chains.",
		},
		"link": schema.MapAttribute{
			Computed:    true,
			Description: "provides additional actions or resources.",
			ElementType: types.StringType,
			CustomType:  customfield.NewMapType[types.String](ctx),
		},
		"locked": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is locked. This field is not required.",
		},
		"mtu_mismatch_detection": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether MTU mismatch detection is enabled on the OSPF interface.",
		},
		"name": schema.StringAttribute{
			Optional:    true,
			Description: "Name of the object.",
		},
		"password": schema.StringAttribute{
			Optional:    true,
			Description: "The password used for OSPF authentication, required if the authentication type is 'password'.",
		},
		"read_only": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is read-only. This field is not required.",
		},
		"retransmit_interval": schema.Int64Attribute{
			Optional:    true,
			Description: "The interval in seconds between retransmissions of OSPF packets.",
		},
		"router_priority": schema.Int64Attribute{
			Optional:    true,
			Description: "The router priority for OSPF, which is used to determine the designated router on a multi-access network.",
		},
		"system": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is a System element. This field is not required.",
		},
		"system_key": schema.Int64Attribute{
			Computed:    true,
			Description: "The system key of the System element. This field is not required.",
		},
		"transmit_delay": schema.Int64Attribute{
			Optional:    true,
			Description: "The delay in seconds before transmitting OSPF packets on the interface.",
		},
		"trashed": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is trashed. This field is not required.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getOspfv2InterfaceSettingsSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetOspfv2InterfaceSettingsSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getOspfv2InterfaceSettingsSchemaBlocksInternal(ctx)
}

func getOspfv2InterfaceSettingsSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{}
}
