// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetAbstractAccessListEntrySchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{}
	if !useHcl2 {
		return attrs
	}

	blocks := getAbstractAccessListEntrySchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetAbstractAccessListEntrySchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getAbstractAccessListEntrySchemaBlocksInternal(ctx)
}

func getAbstractAccessListEntrySchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{
		"as_path_access_list_entry": schema.SingleNestedBlock{
			Description: "This represents an entry in an AS Path Access List, which is used to filter BGP routes based on their AS path.",
			CustomType:  customfield.NewNestedObjectType[AsPathAccessListEntryResourceModel](ctx),
			Attributes:  GetAsPathAccessListEntrySchemaAttributes(ctx),
			Blocks:      GetAsPathAccessListEntrySchemaBlocks(ctx),
		},
		"community_access_list_entry": schema.SingleNestedBlock{
			Description: "This represents an entry in a Community Access List, which is used to filter BGP routes based on BGP communities.",
			CustomType:  customfield.NewNestedObjectType[CommunityAccessListEntryResourceModel](ctx),
			Attributes:  GetCommunityAccessListEntrySchemaAttributes(ctx),
			Blocks:      GetCommunityAccessListEntrySchemaBlocks(ctx),
		},
		"extended_community_access_list_entry": schema.SingleNestedBlock{
			Description: "This represents an entry in an Extended Community Access List, which is used to filter BGP routes based on extended communities.",
			CustomType:  customfield.NewNestedObjectType[ExtendedCommunityAccessListEntryResourceModel](ctx),
			Attributes:  GetExtendedCommunityAccessListEntrySchemaAttributes(ctx),
			Blocks:      GetExtendedCommunityAccessListEntrySchemaBlocks(ctx),
		},
		"ip_access_list_entry": schema.SingleNestedBlock{
			Description: "This represents an entry in an IP Access List, which is used to filter BGP routes based on IP addresses or networks.",
			CustomType:  customfield.NewNestedObjectType[IpAccessListEntryResourceModel](ctx),
			Attributes:  GetIpAccessListEntrySchemaAttributes(ctx),
			Blocks:      GetIpAccessListEntrySchemaBlocks(ctx),
		},
		"ip_prefix_list_entry": schema.SingleNestedBlock{
			Description: "This represents an entry in an IP Prefix List, which is used to filter BGP routes based on IP prefixes.",
			CustomType:  customfield.NewNestedObjectType[IpPrefixListEntryResourceModel](ctx),
			Attributes:  GetIpPrefixListEntrySchemaAttributes(ctx),
			Blocks:      GetIpPrefixListEntrySchemaBlocks(ctx),
		},
		"ipv6_access_list_entry": schema.SingleNestedBlock{
			Description: "This represents an entry in an IPv6 Access List, which is used to filter BGP routes based on IPv6 addresses or networks.",
			CustomType:  customfield.NewNestedObjectType[Ipv6AccessListEntryResourceModel](ctx),
			Attributes:  GetIpv6AccessListEntrySchemaAttributes(ctx),
			Blocks:      GetIpv6AccessListEntrySchemaBlocks(ctx),
		},
		"ipv6_prefix_list_entry": schema.SingleNestedBlock{
			Description: "This represents an entry in an IPv6 Prefix List, which is used to filter BGP routes based on IPv6 prefixes.",
			CustomType:  customfield.NewNestedObjectType[Ipv6PrefixListEntryResourceModel](ctx),
			Attributes:  GetIpv6PrefixListEntrySchemaAttributes(ctx),
			Blocks:      GetIpv6PrefixListEntrySchemaBlocks(ctx),
		},
	}
}
