// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetSslVpnServiceProfileSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Description: "this attribute is the identifier of terraform resource",
		}, "admin_domain": schema.StringAttribute{
			Computed:    true,
			Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
		},
		"authentication_type": schema.StringAttribute{
			Optional:    true,
			Description: "The type of authentication used in the Application Access service profile.",
		},
		"comment": schema.StringAttribute{
			Optional:    true,
			Description: "An optional comment for the element. This field is not required.",
		},
		"cookie_hiding": schema.StringAttribute{
			Optional:    true,
			Description: "The mode for hiding cookies in the Application Access service profile.",
		},
		"etag": schema.StringAttribute{
			Computed:    true,
			Description: "The ETag of the element, used for versioning. This field is not required.",
		},
		"key": schema.Int64Attribute{
			Computed:    true,
			Description: "The unique identifier for the element. This field is required for updates but not for creation.",
		},
		"link": schema.MapAttribute{
			Computed:    true,
			Description: "provides additional actions or resources.",
			ElementType: types.StringType,
			CustomType:  customfield.NewMapType[types.String](ctx),
		},
		"locked": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is locked. This field is not required.",
		},
		"login_page_url": schema.StringAttribute{
			Optional:    true,
			Description: "The URL of the login page for the Application Access service profile.",
		},
		"name": schema.StringAttribute{
			Optional:    true,
			Description: "Name of the object.",
		},
		"ntlm_support": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether NTLM support is enabled in the Application Access service profile.",
		},
		"password_input_name": schema.StringAttribute{
			Optional:    true,
			Description: "The name of the password input field in the Application Access service profile.",
		},
		"post_request_url": schema.StringAttribute{
			Optional:    true,
			Description: "The URL to which the post request is sent in the Application Access service profile.",
		},
		"read_only": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is read-only. This field is not required.",
		},
		"system": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is a System element. This field is not required.",
		},
		"system_key": schema.Int64Attribute{
			Computed:    true,
			Description: "The system key of the System element. This field is not required.",
		},
		"trashed": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is trashed. This field is not required.",
		},
		"user_input_custom_format": schema.StringAttribute{
			Optional:    true,
			Description: "The custom format for user input in the Application Access service profile.",
		},
		"user_input_format": schema.StringAttribute{
			Optional:    true,
			Description: "The format of user input in the Application Access service profile.",
		},
		"user_input_name": schema.StringAttribute{
			Optional:    true,
			Description: "The name of the user input field in the Application Access service profile.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getSslVpnServiceProfileSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetSslVpnServiceProfileSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getSslVpnServiceProfileSchemaBlocksInternal(ctx)
}

func getSslVpnServiceProfileSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{
		"ssl_vpn_http_field": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetSslVpnHttpFieldSchemaAttributes(ctx),
				Blocks:     GetSslVpnHttpFieldSchemaBlocks(ctx),
			},
		},
		"ssl_vpn_profile_exception": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetSslVpnHostnameSchemaAttributes(ctx),
				Blocks:     GetSslVpnHostnameSchemaBlocks(ctx),
			},
		},
	}
}
