// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetSwapFreeSpaceTestSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{"alert_notification": schema.BoolAttribute{
		Optional:    true,
		Description: "Indicates whether an alert notification is sent if the test fails.",
	},
		"comment": schema.StringAttribute{
			Optional:    true,
			Description: "An optional comment for the element. This field is not required.",
		},
		"free_space": schema.Int64Attribute{
			Optional:    true,
			Description: "The minimum amount of free swap space in kilobytes required on the hard disk.",
		},
		"key": schema.Int64Attribute{
			Computed:    true,
			Description: "The unique identifier for the element. This field is required for updates but not for creation.",
		},
		"link": schema.MapAttribute{
			Computed:    true,
			Description: "provides additional actions or resources.",
			ElementType: types.StringType,
			CustomType:  customfield.NewMapType[types.String](ctx),
		},
		"name": schema.StringAttribute{
			Optional:    true,
			Description: "Name of the object.",
		},
		"offline_state": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the test is executed when the engine is offline or not.",
		},
		"online_state": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the test is executed when the engine is online or not.",
		},
		"standby_state": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the test is executed when the engine is in standby state or not.",
		},
		"test_action": schema.StringAttribute{
			Optional:    true,
			Description: "The action to be taken if the test fails. Options include 'none', 'offline', 'forceoffline', and 'forcespeed'.",
		},
		"test_active": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the test is active or not.",
		},
		"test_interval": schema.Int64Attribute{
			Optional:    true,
			Description: "The interval in seconds at which the test is executed. Note! Running a test too frequently can increase overhead.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getSwapFreeSpaceTestSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetSwapFreeSpaceTestSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getSwapFreeSpaceTestSchemaBlocksInternal(ctx)
}

func getSwapFreeSpaceTestSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{}
}
