// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetAutomaticRulesSettingsSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{"alert_ref": schema.StringAttribute{
		Optional:    true,
		Description: "This represents an abstract Alert, which is used to display messages when certain conditions are met.",
	},
		"allow_auth_traffic": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether authentication traffic is allowed for this Automatic Rules Settings.",
		},
		"allow_connections_to_dns_resolvers": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether connections to DNS resolvers are allowed for this Automatic Rules Settings.",
		},
		"allow_connections_to_remote_dhcp_server": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether connections to a remote DHCP server are allowed for this Automatic Rules Settings.",
		},
		"allow_icmp_traffic_for_route_probing": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether ICMP traffic is allowed for route probing in this Automatic Rules Settings.",
		},
		"allow_listening_interfaces_to_dns_relay_port": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether listening interfaces are allowed to relay DNS traffic for this Automatic Rules Settings.",
		},
		"allow_no_nat": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether NAT is allowed to be bypassed for this Automatic Rules Settings.",
		},
		"log_level": schema.StringAttribute{
			Optional:    true,
			Description: "The log level for the Automatic Rules Settings, which defines the verbosity of logging.",
		},
		"qos_class_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a QoS Class, which is an element that links a rule in a QoS Policy to one or more Firewall Actions. The traffic allowed in the access rule is assigned the QoS Class defined for the rule, and the QoS class is used as the matching criteria for applying QoS Policy rules.",
		},
		"vpn_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a Policy Based Virtual Private Network (VPN), which is used to establish secure connections over unsecured networks. It includes various configurations such as NAT rules, mobile VPN topology modes, and associated profiles.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getAutomaticRulesSettingsSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetAutomaticRulesSettingsSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getAutomaticRulesSettingsSchemaBlocksInternal(ctx)
}

func getAutomaticRulesSettingsSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{}
}
