// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetProtocolAgentSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Description: "this attribute is the identifier of terraform resource",
		}, "admin_domain": schema.StringAttribute{
			Computed:    true,
			Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
		},
		"comment": schema.StringAttribute{
			Optional:    true,
			Description: "An optional comment for the element. This field is not required.",
		},
		"deep_inspection_registration_number": schema.Int64Attribute{
			Optional:    true,
			Description: "Internal use: it generates specific registration number when deep inspection is used. This concerns only for fw version <= 5.2.x.",
		},
		"etag": schema.StringAttribute{
			Computed:    true,
			Description: "The ETag of the element, used for versioning. This field is not required.",
		},
		"fallback_agent_id": schema.Int64Attribute{
			Optional:    true,
			Description: "Internal use: Id of the agent that should be used as a fallback.",
		},
		"identifier_situation": schema.Int64Attribute{
			Optional:    true,
			Description: "Internal use: Id of the situation (application) which can be used for identifying this protocol.",
		},
		"key": schema.Int64Attribute{
			Computed:    true,
			Description: "The unique identifier for the element. This field is required for updates but not for creation.",
		},
		"link": schema.MapAttribute{
			Computed:    true,
			Description: "provides additional actions or resources.",
			ElementType: types.StringType,
			CustomType:  customfield.NewMapType[types.String](ctx),
		},
		"locked": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is locked. This field is not required.",
		},
		"module_build": schema.StringAttribute{
			Optional:    true,
			Description: "Dummy module info: build of the sensor module.",
		},
		"module_max_version": schema.StringAttribute{
			Optional:    true,
			Description: "Dummy module info: Max Version (concatenation between ips and fw max version).",
		},
		"module_min_version": schema.StringAttribute{
			Optional:    true,
			Description: "Dummy module info: Min Version (concatenation between ips and fw min version).",
		},
		"module_name": schema.StringAttribute{
			Optional:    true,
			Description: "Dummy module info: name of the sensor module *.so binary file name.",
		},
		"module_upload_always": schema.BoolAttribute{
			Optional:    true,
			Description: "Dummy module info: upload always flag of the sensor module.",
		},
		"name": schema.StringAttribute{
			Optional:    true,
			Description: "Name of the object.",
		},
		"override_module_id": schema.Int64Attribute{
			Optional:    true,
			Description: "Overrides the registration number or system key as the module id, if set. Used for inspection module and sidewinder proxy stacked services.",
		},
		"protocol_matching_in_inspection": schema.BoolAttribute{
			Optional:    true,
			Description: "Flag to know if a protocol can be used in inspection policy, for column Protocol. Default value = true",
		},
		"read_only": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is read-only. This field is not required.",
		},
		"registration_number": schema.Int64Attribute{
			Optional:    true,
			Description: "Internal use: used by the firewall to reference a protocol agent.",
		},
		"supported_protocol": schema.ListAttribute{
			Optional:    true,
			Description: "List of supported protocols: ethernet, ip-proto, tcp, udp, icmp, physical.",
			ElementType: types.StringType,
		},
		"system": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is a System element. This field is not required.",
		},
		"system_key": schema.Int64Attribute{
			Computed:    true,
			Description: "The system key of the System element. This field is not required.",
		},
		"trashed": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is trashed. This field is not required.",
		},
		"type": schema.StringAttribute{
			Optional:    true,
			Description: "The Protocol Agent type.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getProtocolAgentSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetProtocolAgentSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getProtocolAgentSchemaBlocksInternal(ctx)
}

func getProtocolAgentSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{
		"link_selection": schema.SingleNestedBlock{
			Description: "This represents the link selection value used in QoS settings, defining various network parameters such as bandwidth, jitter, latency, packet loss, and stability.",
			CustomType:  customfield.NewNestedObjectType[LinkSelectionValueResourceModel](ctx),
			Attributes:  GetLinkSelectionValueSchemaAttributes(ctx),
			Blocks:      GetLinkSelectionValueSchemaBlocks(ctx),
		},
		"pa_parameters": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetAbstractPaParameterWrapperSchemaAttributes(ctx),
				Blocks:     GetAbstractPaParameterWrapperSchemaBlocks(ctx),
			},
		},
		"pa_values": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetAbstractPaParameterValueWrapperSchemaAttributes(ctx),
				Blocks:     GetAbstractPaParameterValueWrapperSchemaBlocks(ctx),
			},
		},
	}
}
