// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetWebApplicationParametersSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{"client_cert_auth_enabled": schema.BoolAttribute{
		Optional:    true,
		Description: "Indicates whether client authentication is enabled for the Web Application.",
	},
		"context_path": schema.StringAttribute{
			Optional:    true,
			Description: "The context path for the Web Application. If null, it uses the root context.",
		},
		"eca_enabled": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether ECA Rollout evaluation is enabled in SMC Download pages.",
		},
		"enable_saml_for_web_access": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether SAML authentication is enabled for Web Access.",
		},
		"enabled": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the Web Application is enabled or not.",
		},
		"host_name": schema.StringAttribute{
			Optional:    true,
			Description: "The host name for the Web Application. If null, no specific host name is set.",
		},
		"listening_address": schema.StringAttribute{
			Optional:    true,
			Description: "The address on which the Web Application listens for incoming connections. If null, it listens on all addresses.",
		},
		"log_access": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether access to this Web Application is logged.",
		},
		"port": schema.Int64Attribute{
			Optional:    true,
			Description: "The port on which the Web Application listens for incoming connections.",
		},
		"server_credentials_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a TLS Server Credentials element, which is used to store the private key and certificate of an internal server. The certificate and the associated private key must be compatible with OpenSSL and be in PEM format. It is used for TLS inspection, securing Web Access Servers, and authenticating Authentication Servers.",
		},
		"session_timeout": schema.Int64Attribute{
			Optional:    true,
			Description: "The session timeout in seconds for the Web Application, used to control user session duration.",
		},
		"ssl_session_id": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the SSL session ID is used for the Web Application.",
		},
		"standalone_enabled": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether Standalone client bundles download are enabled in SMC Download pages.",
		},
		"tls_cipher_suites": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a TLS Cryptography Suite Set Element, which contains a set of cryptographic suites used in SSL VPN configurations.",
		},
		"web_app_identifier": schema.StringAttribute{
			Optional:    true,
			Description: "The unique identifier for the Web Application, used to reference it in configurations.",
		},
		"webclient_enabled": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the Web UI (React) is enabled in the API page.",
		},
		"xvfb_path": schema.StringAttribute{
			Optional:    true,
			Description: "The full path to the directory containing the xvfb-run application, used for Web Access web app.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getWebApplicationParametersSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetWebApplicationParametersSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getWebApplicationParametersSchemaBlocksInternal(ctx)
}

func getWebApplicationParametersSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{
		"saml_settings": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetSamlSettingsSchemaAttributes(ctx),
				Blocks:     GetSamlSettingsSchemaBlocks(ctx),
			},
		},
	}
}
