// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetSingleSensorSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Description: "this attribute is the identifier of terraform resource",
		}, "active_server_certificate_probing": schema.BoolAttribute{
			Optional:    true,
			Description: "Flag for enabling/disabling TLS probe connections.",
		},
		"active_wait_time": schema.StringAttribute{
			Optional:    true,
			Description: "The Active Wait Time. 'short' Short, 'medium' Medium, 'long' Long.",
		},
		"admin_domain": schema.StringAttribute{
			Computed:    true,
			Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
		},
		"antispoofing_node_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents an Antispoofing Node in the Security Management Client, which is used to protect against malicious packages with altered IP header information.",
		},
		"auto_reboot_timeout": schema.Int64Attribute{
			Optional:    true,
			Description: "The length of time after which an error situation is considered non-recoverable and the engine automatically reboots. The default value is 10 seconds.",
		},
		"comment": schema.StringAttribute{
			Optional:    true,
			Description: "An optional comment for the element. This field is not required.",
		},
		"connection_limit": schema.Int64Attribute{
			Optional:    true,
			Description: "Sets a limit for connections from a single source and/or destination IP address. When the set number of connections is reached, the next connection attempts are blocked by the engine until a previously open connection is closed.",
		},
		"contact_timeout": schema.Int64Attribute{
			Optional:    true,
			Description: "Used when opening any kind of communication between the Management Server and the engines. A consistently slow network connection may require increasing this value. The default value is 60 seconds.",
		},
		"custom_properties_profile": schema.ListAttribute{
			Optional:    true,
			Description: "URI of the custom properties profile.",
			ElementType: types.StringType,
		},
		"destination_server_certificate_cache_timeout": schema.Int64Attribute{
			Optional:    true,
			Description: "The timeout value for certificate entries in the cache in minutes.",
		},
		"discard_quic_if_cant_inspect": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether QUIC traffic should be discarded when inspection is not possible.",
		},
		"dos_protection": schema.StringAttribute{
			Optional:    true,
			Description: "The DOS Protection Mode, which can be set to 'always_off', 'default_off', or 'default_on'. This determines the level of DoS protection applied to the VSS Context.",
		},
		"engine_version": schema.StringAttribute{
			Optional:    true,
			Description: "The version of the engine that this cluster is running.",
		},
		"etag": schema.StringAttribute{
			Computed:    true,
			Description: "The ETag of the element, used for versioning. This field is not required.",
		},
		"fuid_network_filter": schema.ListAttribute{
			Optional:    true,
			Description: "The network filtering address ranges for the engine. It is used by the firewall to restrict the range of events to be received from the FUID server.",
			ElementType: types.StringType,
		},
		"geolocation_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents the definition of a geolocation. A Geolocation object keeps a list of Network Elements belonging to the same geolocation.",
		},
		"granted_policy_ref": schema.ListAttribute{
			Optional:    true,
			Description: "URI of the granted policies.",
			ElementType: types.StringType,
		},
		"half_open_connections": schema.Int64Attribute{
			Optional:    true,
			Description: "The number of Half Open Connections allowed. If not specified, it defaults to 125.",
		},
		"icap_dlp_server_ref": schema.ListAttribute{
			Optional:    true,
			Description: "URI of the ICAP Server.",
			ElementType: types.StringType,
		},
		"inspection_cpu_balancing_mode": schema.StringAttribute{
			Optional:    true,
			Description: "The Inspection CPU Balancing Mode. 'default' Default value, 'round_robin' Round Robin, 'numa' NUMA local Round Robin.",
		},
		"integrated_uis_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents an Integrated User Identification Service, which is used to identify users based on their network activity. It allows for integration with authentication domains and provides configuration options for initial query time, polling interval, and ignore values.",
		},
		"is_cert_auto_renewal": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether automated certificate renewal is enabled for this cluster.",
		},
		"is_config_encrypted": schema.BoolAttribute{
			Optional:    true,
			Description: "Is the configuration file encrypted?",
		},
		"is_icap_dlp_enabled": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether ICAP DLP (Data Loss Prevention) is enabled.",
		},
		"is_snort_enabled": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether Snort intrusion detection and prevention is enabled for the firewall cluster.",
		},
		"is_snort_file_defined": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether a Snort configuration file is defined for the firewall cluster.",
		},
		"is_virtual_defrag": schema.BoolAttribute{
			Optional:    true,
			Description: "Enables a procedure in which incoming packet fragments are collected, defragmented for processing by the engine, and refragmented before transmission. This is useful for handling fragmented packets in the network.",
		},
		"key": schema.Int64Attribute{
			Computed:    true,
			Description: "The unique identifier for the element. This field is required for updates but not for creation.",
		},
		"link": schema.MapAttribute{
			Computed:    true,
			Description: "provides additional actions or resources.",
			ElementType: types.StringType,
			CustomType:  customfield.NewMapType[types.String](ctx),
		},
		"lldp_profile_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a LLDP Profile, which is used to configure the LLDP (Link Layer Discovery Protocol) settings for devices.",
		},
		"location_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents the definition of a Location, which keeps a list of Network Elements belonging to the same location.",
		},
		"locked": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is locked. This field is not required.",
		},
		"log_buffer_size": schema.Int64Attribute{
			Optional:    true,
			Description: "The size of the log buffer in bytes. If not specified, it defaults to 1048576 bytes (1 MB).",
		},
		"log_server_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a Log Server, which is a component of the Management Center responsible for storing and managing log (and alert) data, and analyzing and correlating events detected by multiple NGFW Engines.",
		},
		"log_spooling_policy": schema.StringAttribute{
			Optional:    true,
			Description: "The Log Spooling Policy that defines what happens when the engine's log spool becomes full. It can be set to 'stop' (Stop Traffic) or 'discard' (Discard Log).",
		},
		"max_spooled_conf_count": schema.Int64Attribute{
			Optional:    true,
			Description: "The maximum number of configurations that can be spooled. If not specified, it defaults to 1000.",
		},
		"name": schema.StringAttribute{
			Optional:    true,
			Description: "Name of the object.",
		},
		"nondecrypted_ca_certificate_ref": schema.ListAttribute{
			Optional:    true,
			Description: "URI of the non-decrypted CA certificates.",
			ElementType: types.StringType,
		},
		"nondecrypted_tls_server_credentials_ref": schema.ListAttribute{
			Optional:    true,
			Description: "URI of the non-decrypted TLS server credentials.",
			ElementType: types.StringType,
		},
		"passive_discard_access_mode": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether passive discard mode is enabled for connections that match rules with the Terminate action in the Access Rules. When enabled, it does not stop matching connections but creates a special log entry for testing purposes.",
		},
		"passive_discard_mode": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the Passive Discard Mode is enabled. If true, it does not stop matching connections but creates a special log entry Terminate (passive) for testing purposes.",
		},
		"read_only": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is read-only. This field is not required.",
		},
		"reporting_email_addresses": schema.StringAttribute{
			Optional:    true,
			Description: "The contact email address for reporting per sender.",
		},
		"rollback_timeout": schema.Int64Attribute{
			Optional:    true,
			Description: "The time the engine waits for a management connection before it rolls back to the previously installed policy when the Policy Handshake option is active. The default value is 60 seconds.",
		},
		"routing_node_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a Routing Node in the Security Management Client, which is used to configure routing for network traffic on firewalls.",
		},
		"sandbox_type": schema.StringAttribute{
			Optional:    true,
			Description: "The Sandbox service selection.",
		},
		"send_reset_for_out_of_state_tcp_packets": schema.StringAttribute{
			Optional:    true,
			Description: "The engine refuses TCP connections if the TCP connection does not start with a SYN packet, even if the TCP connection matches an Access rule with the Allow action.",
		},
		"server_credential": schema.ListAttribute{
			Optional:    true,
			Description: "URI of the TLS Server Credentials.",
			ElementType: types.StringType,
		},
		"slow_request_block_list_timeout": schema.Int64Attribute{
			Optional:    true,
			Description: "The DOS Protection Slow Request Block List timeout in seconds. If not specified, it defaults to 60 seconds.",
		},
		"slow_request_sensitivity": schema.StringAttribute{
			Optional:    true,
			Description: "The DOS Protection Slow Request Sensitivity, which can be set to 'off', 'low', 'medium', or 'high'. This determines the sensitivity level for detecting slow requests.",
		},
		"snmp_agent_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents an SNMP Agent. It contains the configuration details for SNMP (Simple Network Management Protocol) on an engine, including SNMP version, users, monitoring settings, and trap destinations.",
		},
		"snmp_location": schema.StringAttribute{
			Optional:    true,
			Description: "The location for the current SNMP client.",
		},
		"strict_tcp_mode": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether Strict TCP mode is enabled. When enabled, it provides enhanced protection against TCP evasion attempts by controlling the progress of a TCP connection and enforcing strict adherence to the TCP protocol.",
		},
		"syn_flood_sensitivity": schema.StringAttribute{
			Optional:    true,
			Description: "The DOS Protection Syn Flood Sensitivity, which can be set to 'off', 'low', 'medium', or 'high'. This determines the sensitivity level for detecting SYN flood attacks.",
		},
		"syn_max_bursts": schema.Int64Attribute{
			Optional:    true,
			Description: "The SYN Burst Size value (>= 1). The number of allowed SYNs before the engine starts limiting the SYN rate.",
		},
		"syn_mode": schema.StringAttribute{
			Optional:    true,
			Description: "The SYN Rate Limits Mode. 'off' SYN Rate Limits are disabled. This is the default setting. 'auto' The engine automatically calculates the number of Allowed SYNs per Second and the Burst Size for the interface based on the engine's capacity and memory size. 'custom' Enter the desired values for Allowed SYNs per Second and Burst Size. We recommend that the Burst Size be at least one tenth of the Allowed SYNs per Second value. If the Burst Size is too small, SYN Rate Limits do not work.",
		},
		"syn_per_second": schema.Int64Attribute{
			Optional:    true,
			Description: "The Allowed SYNs per Second value (>= 1). The number of allowed SYN packets per second.",
		},
		"system": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is a System element. This field is not required.",
		},
		"system_key": schema.Int64Attribute{
			Computed:    true,
			Description: "The system key of the System element. This field is not required.",
		},
		"tcp_reset_sensitivity": schema.StringAttribute{
			Optional:    true,
			Description: "The DOS TCP Reset Sensitivity, which can be set to 'off', 'low', 'medium', or 'high'. This determines the sensitivity level for TCP reset actions.",
		},
		"timezone": schema.StringAttribute{
			Optional:    true,
			Description: "The timezone setting for the firewall, which determines the local time zone used by the system.",
		},
		"tls_crl_checks": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the engine performs CRL checks for TLS certificates.",
		},
		"tls_cryptography_suite_set_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a TLS Cryptography Suite Set Element, which contains a set of cryptographic suites used in SSL VPN configurations.",
		},
		"tls_deny_decrypting": schema.BoolAttribute{
			Optional:    true,
			Description: "Indicates whether the engine denies decrypting TLS traffic.",
		},
		"tools_profile_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a Tools Profile. Tools Profiles add commands to the right-click menus of elements, allowing dynamic information inclusion from the element definition. Only one Tools Profile can be selected for each element, but each can include several commands. Commands are launched on the workstation running the Management Client and are operating-system-specific.",
		},
		"tracking_mode": schema.StringAttribute{
			Optional:    true,
			Description: "The Connection Tracking Mode. 'normal' When selected, the engine drops ICMP error messages related to connections that are not currently active in connection tracking. A valid, complete TCP handshake is required for TCP traffic. The engine checks the traffic direction and the port parameters of UDP traffic. 'strict' When selected, the engine does not permit TCP traffic to pass through before a complete, valid TCP handshake is performed. 'loose' When selected, the engine allows some connection patterns and address translation operations that are not allowed in the Normal mode. Note! You can override this general setting and configure connection tracking for TCP, UDP, and ICMP traffic in Access rules.",
		},
		"trashed": schema.BoolAttribute{
			Computed:    true,
			Description: "Indicates if the element is trashed. This field is not required.",
		},
		"user_id_service_ref": schema.StringAttribute{
			Optional:    true,
			Description: "This represents a User ID Service element, which is used to manage user identification services. It includes attributes for port, IP addresses, monitored user domains, cache expiration, connect timeout, TLS profile, and TLS identity.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getSingleSensorSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetSingleSensorSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getSingleSensorSchemaBlocksInternal(ctx)
}

func getSingleSensorSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{
		"advanced_multilink_settings": schema.SingleNestedBlock{
			Description: "This represents the advanced Multi-Link settings for the engine, which includes failover thresholds, probe thresholds, and initial values for various parameters.",
			CustomType:  customfield.NewNestedObjectType[AdvancedMultiLinkSettingsResourceModel](ctx),
			Attributes:  GetAdvancedMultiLinkSettingsSchemaAttributes(ctx),
			Blocks:      GetAdvancedMultiLinkSettingsSchemaBlocks(ctx),
		},
		"alias_value": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetAliasValueSchemaAttributes(ctx),
				Blocks:     GetAliasValueSchemaBlocks(ctx),
			},
		},
		"antivirus": schema.SingleNestedBlock{
			Description: "This represents the settings for the antivirus feature on a firewall element, including antivirus enablement, log levels, update frequencies, and proxy settings.",
			CustomType:  customfield.NewNestedObjectType[AntivirusSettingsResourceModel](ctx),
			Attributes:  GetAntivirusSettingsSchemaAttributes(ctx),
			Blocks:      GetAntivirusSettingsSchemaBlocks(ctx),
		},
		"automatic_rules_settings": schema.SingleNestedBlock{
			Description: "This represents the Automatic Rules Settings for the Engine Cluster, including VPN, QoS Class, Alert, and various traffic control settings.",
			CustomType:  customfield.NewNestedObjectType[AutomaticRulesSettingsResourceModel](ctx),
			Attributes:  GetAutomaticRulesSettingsSchemaAttributes(ctx),
			Blocks:      GetAutomaticRulesSettingsSchemaBlocks(ctx),
		},
		"certificate_validation_settings": schema.SingleNestedBlock{
			Description: "This defines settings for certificate validation on the engine, including OCSP and CRL lookups, timeout settings, and optional HTTP proxy configuration.",
			CustomType:  customfield.NewNestedObjectType[CertificateValidationSettingsResourceModel](ctx),
			Attributes:  GetCertificateValidationSettingsSchemaAttributes(ctx),
			Blocks:      GetCertificateValidationSettingsSchemaBlocks(ctx),
		},
		"connection_timeout": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetIdleTimeoutSchemaAttributes(ctx),
				Blocks:     GetIdleTimeoutSchemaBlocks(ctx),
			},
		},
		"domain_server_address": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetDnsElementSchemaAttributes(ctx),
				Blocks:     GetDnsElementSchemaBlocks(ctx),
			},
		},
		"eca_settings": schema.SingleNestedBlock{
			Description: "This represents the definition of ECA settings feature, which includes client and server networks, listened zones, listened interfaces, and listening port.",
			CustomType:  customfield.NewNestedObjectType[EcaSettingsResourceModel](ctx),
			Attributes:  GetEcaSettingsSchemaAttributes(ctx),
			Blocks:      GetEcaSettingsSchemaBlocks(ctx),
		},
		"file_reputation_settings": schema.SingleNestedBlock{
			Description: "This represents the File Reputation settings for the Engine Cluster, including the file reputation context and HTTP proxies.",
			CustomType:  customfield.NewNestedObjectType[FileReputationSettingsResourceModel](ctx),
			Attributes:  GetFileReputationSettingsSchemaAttributes(ctx),
			Blocks:      GetFileReputationSettingsSchemaBlocks(ctx),
		},
		"local_log_storage": schema.SingleNestedBlock{
			Description: "This represents the Local Log Storage settings for the FWIPSCluster, which is not applicable to virtual engines.",
			CustomType:  customfield.NewNestedObjectType[LocalLogStorageSettingsResourceModel](ctx),
			Attributes:  GetLocalLogStorageSettingsSchemaAttributes(ctx),
			Blocks:      GetLocalLogStorageSettingsSchemaBlocks(ctx),
		},
		"log_moderation": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetLogModerationSchemaAttributes(ctx),
				Blocks:     GetLogModerationSchemaBlocks(ctx),
			},
		},
		"nodes": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetEngineNodeWrapperSchemaAttributes(ctx),
				Blocks:     GetEngineNodeWrapperSchemaBlocks(ctx),
			},
		},
		"ntp_settings": schema.SingleNestedBlock{
			Description: "This represents the definition of NTP settings, which includes enabling NTP, defining NTP servers, and setting a preferred NTP server.",
			CustomType:  customfield.NewNestedObjectType[NtpSettingsResourceModel](ctx),
			Attributes:  GetNtpSettingsSchemaAttributes(ctx),
			Blocks:      GetNtpSettingsSchemaBlocks(ctx),
		},
		"physical_interfaces": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetAbstractPhysicalInterfaceWrapperSchemaAttributes(ctx),
				Blocks:     GetAbstractPhysicalInterfaceWrapperSchemaBlocks(ctx),
			},
		},
		"sandbox_settings": schema.SingleNestedBlock{
			Description: "This represents the definition of Sandbox settings feature, which includes configuration for sandbox service, license key, license token, and HTTP proxies.",
			CustomType:  customfield.NewNestedObjectType[SandboxSettingsResourceModel](ctx),
			Attributes:  GetSandboxSettingsSchemaAttributes(ctx),
			Blocks:      GetSandboxSettingsSchemaBlocks(ctx),
		},
		"scan_detection": schema.SingleNestedBlock{
			Description: "This represents the definition of Scan Detection settings on a NGFW, including scan detection type, time windows, events sensitivity, and logging options.",
			CustomType:  customfield.NewNestedObjectType[ScanDetectionSettingsResourceModel](ctx),
			Attributes:  GetScanDetectionSettingsSchemaAttributes(ctx),
			Blocks:      GetScanDetectionSettingsSchemaBlocks(ctx),
		},
		"snmp_interface": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetSnmpInterfaceEntrySchemaAttributes(ctx),
				Blocks:     GetSnmpInterfaceEntrySchemaBlocks(ctx),
			},
		},
		"tester_parameters": schema.SingleNestedBlock{
			Description: "This represents the Tester Global Settings defined for an engine, including alert intervals, boot delays, and recovery options.",
			CustomType:  customfield.NewNestedObjectType[TesterParametersResourceModel](ctx),
			Attributes:  GetTesterParametersSchemaAttributes(ctx),
			Blocks:      GetTesterParametersSchemaBlocks(ctx),
		},
		"tests": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: GetTestEntryWrapperSchemaAttributes(ctx),
				Blocks:     GetTestEntryWrapperSchemaBlocks(ctx),
			},
		},
		"tls_client_protection": schema.SingleNestedBlock{
			Description: "This represents a wrapper for TLS Client protection settings, including proxy usage and trusted certificate authorities.",
			CustomType:  customfield.NewNestedObjectType[TlsClientProtectionWrapperResourceModel](ctx),
			Attributes:  GetTlsClientProtectionWrapperSchemaAttributes(ctx),
			Blocks:      GetTlsClientProtectionWrapperSchemaBlocks(ctx),
		},
		"ts_settings": schema.SingleNestedBlock{
			Description: "This represents the definition of Threat Seeker settings, which includes enabling/disabling Threat Seeker and configuring HTTP proxies.",
			CustomType:  customfield.NewNestedObjectType[ThreatSeekerSettingsResourceModel](ctx),
			Attributes:  GetThreatSeekerSettingsSchemaAttributes(ctx),
			Blocks:      GetThreatSeekerSettingsSchemaBlocks(ctx),
		},
	}
}
