#!/bin/bash
# Generic script to run Go commands inside the CI Docker container

set -e

IMAGE=go-docker

# Ensure .cache directories exist for golangci-lint, go build, go mod, and gopath
mkdir -p .cache .cache/go-build .cache/gomod .cache/gopath

# Run the provided command inside the container, preserving user rights and using writable caches
CMD=("$@")
docker run --rm -u $(id -u):$(id -g) \
    -v "$(pwd)":/app -w /app \
    -v "$(pwd)/.cache":/app/.cache \
    -v "$(pwd)/.cache/go-build":/app/.cache/go-build \
    -v "$(pwd)/.cache/gomod":/app/.cache/gomod \
    -v "$(pwd)/.cache/gopath":/app/.cache/gopath \
    -v  "$(pwd)/.cache/":/.cache \
    -e GOLANGCI_LINT_CACHE=/app/.cache \
    -e GOCACHE=/app/.cache/go-build \
    -e GOMODCACHE=/app/.cache/gomod \
    -e GOPATH=/app/.cache/gopath \
    $IMAGE "${CMD[@]}"
