// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Export_Log_Task

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/terraform-providers/terraform-provider-smc/internal/customfield"
    "fmt"
	"context"

)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()



type ExportLogTaskResourceModel struct {
	
	ID                    types.String `tfsdk:"id"`
    AdminDomain types.String `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
        Comment types.String `tfsdk:"comment" json:"comment,optional,omitempty" `
        DeleteSourceData types.Bool `tfsdk:"delete_source_data" json:"delete_source_data,optional,omitempty" `
        EndTime types.Int64 `tfsdk:"end_time" json:"end_time,optional,omitempty" `
        Etag types.String `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
        FileFormat types.String `tfsdk:"file_format" json:"file_format,optional,omitempty" `
        FileName types.String `tfsdk:"file_name" json:"file_name,optional,omitempty" `
        FilterForDelete types.String `tfsdk:"filter_for_delete" json:"filter_for_delete,optional,omitempty" `
        FilterForExport types.String `tfsdk:"filter_for_export" json:"filter_for_export,optional,omitempty" `
        ForAlertEventLog types.Bool `tfsdk:"for_alert_event_log" json:"for_alert_event_log,optional,omitempty" `
        ForAlertLog types.Bool `tfsdk:"for_alert_log" json:"for_alert_log,optional,omitempty" `
        ForAuditLog types.Bool `tfsdk:"for_audit_log" json:"for_audit_log,optional,omitempty" `
        ForFwLog types.Bool `tfsdk:"for_fw_log" json:"for_fw_log,optional,omitempty" `
        ForIpsLog types.Bool `tfsdk:"for_ips_log" json:"for_ips_log,optional,omitempty" `
        ForIpsRecordingLog types.Bool `tfsdk:"for_ips_recording_log" json:"for_ips_recording_log,optional,omitempty" `
        ForL2fwLog types.Bool `tfsdk:"for_l2fw_log" json:"for_l2fw_log,optional,omitempty" `
        ForThirdPartyLog types.Bool `tfsdk:"for_third_party_log" json:"for_third_party_log,optional,omitempty" `
        IpsRecordings *[]types.Int64 `tfsdk:"ips_recordings" json:"ips_recordings,optional,omitempty" `
        IsLocalLocation types.Bool `tfsdk:"is_local_location" json:"is_local_location,optional,omitempty" `
        Key types.Int64 `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
        Link customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"link" json:"link,optional,omitempty" fpro:"link"`
        Lk customfield.Map[types.String] `tfsdk:"lk" json:"-" `
        Locked types.Bool `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
        Name types.String `tfsdk:"name" json:"name,optional,omitempty" `
        OverwriteFileFlag types.String `tfsdk:"overwrite_file_flag" json:"overwrite_file_flag,optional,omitempty" `
        ReadOnly types.Bool `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
        RelativeTimeBegin types.Int64 `tfsdk:"relative_time_begin" json:"relative_time_begin,optional,omitempty" `
        RelativeTimeEnd types.Int64 `tfsdk:"relative_time_end" json:"relative_time_end,optional,omitempty" `
        Resources *[]types.String `tfsdk:"resources" json:"resources,optional,omitempty" `
        ScriptName types.String `tfsdk:"script_name" json:"script_name,optional,omitempty" `
        ServerDirectories *[]ServerDirectoriesResourceModel `tfsdk:"server_directories" json:"server_directories,optional,omitempty" `
        StartTime types.Int64 `tfsdk:"start_time" json:"start_time,optional,omitempty" `
        System types.Bool `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
        SystemKey types.Int64 `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
        TimeLimitType types.String `tfsdk:"time_limit_type" json:"time_limit_type,optional,omitempty" `
        Trashed types.Bool `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
        
}
func (r *ExportLogTaskResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}