// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Loopback_EndPoint

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type LoopbackEndpointResourceModel struct {
	ID                types.String                                       `tfsdk:"id"`
	FromRef           types.String                                       `tfsdk:"from_ref"`
	Address           types.String                                       `tfsdk:"address" json:"address,optional,omitempty" `
	AdminDomain       types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	Comment           types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	ConnectionTypeRef types.String                                       `tfsdk:"connection_type_ref" json:"connection_type_ref,optional,omitempty" `
	DeductedName      types.String                                       `tfsdk:"deducted_name" json:"deducted_name,optional,omitempty" `
	Dynamic           types.Bool                                         `tfsdk:"dynamic" json:"dynamic,optional,omitempty" `
	Enabled           types.Bool                                         `tfsdk:"enabled" json:"enabled,optional,omitempty" `
	Etag              types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	ForceNatT         types.Bool                                         `tfsdk:"force_nat_t" json:"force_nat_t,optional,omitempty" `
	IkePhase1IdType   types.String                                       `tfsdk:"ike_phase1_id_type" json:"ike_phase1_id_type,optional,omitempty" `
	IkePhase1IdValue  types.String                                       `tfsdk:"ike_phase1_id_value" json:"ike_phase1_id_value,optional,omitempty" `
	IpsecVpn          types.Bool                                         `tfsdk:"ipsec_vpn" json:"ipsec_vpn,optional,omitempty" `
	Key               types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link              customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked            types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	Name              types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	NatT              types.Bool                                         `tfsdk:"nat_t" json:"nat_t,optional,omitempty" `
	ReadOnly          types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	SslVpnPortal      types.Bool                                         `tfsdk:"ssl_vpn_portal" json:"ssl_vpn_portal,optional,omitempty" `
	SslVpnTunnel      types.Bool                                         `tfsdk:"ssl_vpn_tunnel" json:"ssl_vpn_tunnel,optional,omitempty" `
	System            types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey         types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Trashed           types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
	UdpEncapsulation  types.Bool                                         `tfsdk:"udp_encapsulation" json:"udp_encapsulation,optional,omitempty" `
}

func (r *LoopbackEndpointResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}
