// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Internal_User_Group

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type InternalUserGroupResourceModel struct {
	ID                   types.String                                       `tfsdk:"id"`
	ActivationDate       types.Int64                                        `tfsdk:"activation_date" json:"activation_date,optional,omitempty" `
	AdminDomain          types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	AuthenticationMethod *[]types.String                                    `tfsdk:"authentication_method" json:"authentication_method,optional,omitempty" `
	Comment              types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	Etag                 types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	ExpirationAfter      types.Int64                                        `tfsdk:"expiration_after" json:"expiration_after,optional,omitempty" `
	ExpirationDate       types.Int64                                        `tfsdk:"expiration_date" json:"expiration_date,optional,omitempty" `
	Key                  types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                 customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                   customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked               types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	Member               *[]types.String                                    `tfsdk:"member" json:"member,optional,omitempty" `
	Name                 types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	ReadOnly             types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	SubjectAltNames      types.String                                       `tfsdk:"subject_alt_names" json:"subject_alt_names,optional,omitempty" `
	System               types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey            types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Trashed              types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
	UniqueId             types.String                                       `tfsdk:"unique_id" json:"unique_id,optional,omitempty" `
	UserDomain           types.String                                       `tfsdk:"user_domain" json:"user_domain,optional,omitempty" `
}

func (r *InternalUserGroupResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}
