// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: VSS_Container_Node_ISC_Settings

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/terraform-providers/terraform-provider-smc/internal/customfield"
    "fmt"
	"context"

)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()



type VssContainerNodeIscSettingsResourceModel struct {
	
	ID                    types.String `tfsdk:"id"`
	FromRef              types.String `tfsdk:"from_ref"`
    Comment types.String `tfsdk:"comment" json:"comment,optional,omitempty" `
        ContactIp types.String `tfsdk:"contact_ip" json:"contact_ip,optional,omitempty" `
        IscHypervisor types.String `tfsdk:"isc_hypervisor" json:"isc_hypervisor,optional,omitempty" `
        Key types.Int64 `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
        Link customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"link" json:"link,optional,omitempty" fpro:"link"`
        Lk customfield.Map[types.String] `tfsdk:"lk" json:"-" `
        ManagementGateway types.String `tfsdk:"management_gateway" json:"management_gateway,optional,omitempty" `
        ManagementIp types.String `tfsdk:"management_ip" json:"management_ip,optional,omitempty" `
        ManagementNetmask types.Int64 `tfsdk:"management_netmask" json:"management_netmask,optional,omitempty" `
        Name types.String `tfsdk:"name" json:"name,optional,omitempty" `
        
}
func (r *VssContainerNodeIscSettingsResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}