// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Test_Entry_Wrapper

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/terraform-providers/terraform-provider-smc/internal/customfield"
    "fmt"
	"context"

)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()



type TestEntryWrapperResourceModel struct {
	
    Dto *AbstractTestEntryResourceModel `tfsdk:"dto" json:"dto,optional,omitempty" `
        Type types.String `tfsdk:"type" json:"type,optional,omitempty" `
        
}