// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Backup_Task

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/terraform-providers/terraform-provider-smc/internal/customfield"
    "fmt"
	"context"

)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()



type BackupTaskResourceModel struct {
	
	ID                    types.String `tfsdk:"id"`
    AdminDomain types.String `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
        BackupComment types.String `tfsdk:"backup_comment" json:"backup_comment,optional,omitempty" `
        Comment types.String `tfsdk:"comment" json:"comment,optional,omitempty" `
        Etag types.String `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
        Key types.Int64 `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
        Link customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"link" json:"link,optional,omitempty" fpro:"link"`
        Lk customfield.Map[types.String] `tfsdk:"lk" json:"-" `
        Locked types.Bool `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
        LogDataMustBeSaved types.Bool `tfsdk:"log_data_must_be_saved" json:"log_data_must_be_saved,optional,omitempty" `
        Name types.String `tfsdk:"name" json:"name,optional,omitempty" `
        Password types.String `tfsdk:"password" json:"password,optional,omitempty" `
        ReadOnly types.Bool `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
        Resources *[]types.String `tfsdk:"resources" json:"resources,optional,omitempty" `
        ScriptToExecute types.String `tfsdk:"script_to_execute" json:"script_to_execute,optional,omitempty" `
        ServerPath types.String `tfsdk:"server_target_path" json:"server_target_path,optional,omitempty" `
        System types.Bool `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
        SystemKey types.Int64 `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
        Trashed types.Bool `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
        
}
func (r *BackupTaskResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}