// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: External_Authentication_Method

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/terraform-providers/terraform-provider-smc/internal/customfield"
    "fmt"
	"context"

)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()



type ExternalAuthenticationMethodResourceModel struct {
	
	ID                    types.String `tfsdk:"id"`
    AdminDomain types.String `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
        AuthenticationServer *[]AuthenticationMethodContainerForStorageResourceModel `tfsdk:"authentication_server" json:"authentication_server,optional,omitempty" `
        Comment types.String `tfsdk:"comment" json:"comment,optional,omitempty" `
        Etag types.String `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
        Key types.Int64 `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
        Link customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"link" json:"link,optional,omitempty" fpro:"link"`
        Lk customfield.Map[types.String] `tfsdk:"lk" json:"-" `
        Locked types.Bool `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
        Name types.String `tfsdk:"name" json:"name,optional,omitempty" `
        OpenIdClientId types.String `tfsdk:"open_id_client_id" json:"open_id_client_id,optional,omitempty" `
        OpenIdSecret types.String `tfsdk:"open_id_secret" json:"open_id_secret,optional,omitempty" `
        OpenIdTrustedCertRef types.String `tfsdk:"open_id_trusted_cert_ref" json:"open_id_trusted_cert_ref,optional,omitempty" `
        OpenIdUrl types.String `tfsdk:"open_id_url" json:"open_id_url,optional,omitempty" `
        OpenIdUserAttribute types.String `tfsdk:"open_id_user_attribute" json:"open_id_user_attribute,optional,omitempty" `
        ReadOnly types.Bool `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
        SamlGroupAttrName *[]types.String `tfsdk:"saml_group_attr_name" json:"saml_group_attr_name,optional,omitempty" `
        SamlMetadataFile types.String `tfsdk:"saml_metadata_file" json:"saml_metadata_file,optional,omitempty" `
        SamlTlsProfileRef types.String `tfsdk:"saml_tls_profile_ref" json:"saml_tls_profile_ref,optional,omitempty" `
        System types.Bool `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
        SystemKey types.Int64 `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
        Trashed types.Bool `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
        Type types.String `tfsdk:"type" json:"type,optional,omitempty" `
        
}
func (r *ExternalAuthenticationMethodResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}