// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Update_Package

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/terraform-providers/terraform-provider-smc/internal/customfield"
    "fmt"
	"context"

)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()



type UpdatePackageResourceModel struct {
	
	ID                    types.String `tfsdk:"id"`
    ActivationDate types.Int64 `tfsdk:"activation_date" json:"activation_date,optional,omitempty" fpro:"activation_date"`
        AdminDomain types.String `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
        Comment types.String `tfsdk:"comment" json:"comment,optional,omitempty" `
        Etag types.String `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
        Key types.Int64 `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
        Link customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"link" json:"link,optional,omitempty" fpro:"link"`
        Lk customfield.Map[types.String] `tfsdk:"lk" json:"-" `
        Locked types.Bool `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
        Name types.String `tfsdk:"name" json:"name,optional,omitempty" `
        PackageId types.Int64 `tfsdk:"package_id" json:"package_id,optional,omitempty" fpro:"package_id"`
        ReadOnly types.Bool `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
        ReleaseDate types.String `tfsdk:"release_date" json:"release_date,optional,omitempty" fpro:"release_date"`
        SmcVersion types.String `tfsdk:"smc_version" json:"smc_version,optional,omitempty" fpro:"smc_version"`
        State types.String `tfsdk:"state" json:"state,optional,omitempty" fpro:"state"`
        System types.Bool `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
        SystemKey types.Int64 `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
        Trashed types.Bool `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
        
}
func (r *UpdatePackageResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}