// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: IP_Address_List

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/terraform-providers/terraform-provider-smc/internal/customfield"
    "fmt"
	"context"

)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()



type IpAddressListResourceModel struct {
	
	ID                    types.String `tfsdk:"id"`
	FromRef              types.String `tfsdk:"from_ref"`
    Ip *[]types.String `tfsdk:"ip" json:"ip,optional,omitempty" `
        Name types.String `tfsdk:"name" json:"name,optional,omitempty" `
        
}
func (r *IpAddressListResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.ValueString()}
}