// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: System_Snapshot
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &SystemSnapshotResource{}
var _ resource.ResourceWithImportState = &SystemSnapshotResource{}
var _ context.Context = context.Background()


// SystemSnapshotResource defines the resource implementation.
type SystemSnapshotResource struct {
    ResourceBase[SystemSnapshotResourceModel]
}


// Schema defines the schema for the SystemSnapshot resource.
func (r *SystemSnapshotResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a System Snapshot, which is a record of system elements defined within a specific update package. It helps in tracking changes after the activation of an update package.",
      Attributes: GetSystemSnapshotSchemaAttributes(ctx),
      Blocks: GetSystemSnapshotSchemaBlocks(ctx),
    } // schema
    

}

// NewSystemSnapshotResource creates a new instance of the SystemSnapshot resource.
func NewSystemSnapshotResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing SystemSnapshot resource")
	r := &SystemSnapshotResource{
        ResourceBase: ResourceBase[SystemSnapshotResourceModel]{
             resourceType: "system_snapshot",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}