// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Custom_Alert
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &CustomAlertResource{}
var _ resource.ResourceWithImportState = &CustomAlertResource{}
var _ context.Context = context.Background()


// CustomAlertResource defines the resource implementation.
type CustomAlertResource struct {
    ResourceBase[CustomAlertResourceModel]
}


// Schema defines the schema for the CustomAlert resource.
func (r *CustomAlertResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a custom Alert, which is used to define and manage custom alert events in the system.",
      Attributes: GetCustomAlertSchemaAttributes(ctx),
      Blocks: GetCustomAlertSchemaBlocks(ctx),
    } // schema
    

}

// NewCustomAlertResource creates a new instance of the CustomAlert resource.
func NewCustomAlertResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing CustomAlert resource")
	r := &CustomAlertResource{
        ResourceBase: ResourceBase[CustomAlertResourceModel]{
             resourceType: "alert",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}