// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Master_Node
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &MasterNodeResource{}
var _ resource.ResourceWithImportState = &MasterNodeResource{}
var _ context.Context = context.Background()


// MasterNodeResource defines the resource implementation.
type MasterNodeResource struct {
    ResourceBase[MasterNodeResourceModel]
}


// Schema defines the schema for the MasterNode resource.
func (r *MasterNodeResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an individual Master NGFW Engine node in the Security Management Client, representing a device that runs firewall software as part of a Master NGFW Engine.",
      Attributes: GetMasterNodeSchemaAttributes(ctx),
      Blocks: GetMasterNodeSchemaBlocks(ctx),
    } // schema
    

}

// NewMasterNodeResource creates a new instance of the MasterNode resource.
func NewMasterNodeResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing MasterNode resource")
	r := &MasterNodeResource{
        ResourceBase: ResourceBase[MasterNodeResourceModel]{
             resourceType: "master_node",
             isSubResource: true,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}