// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Regexp_Situation_Parameter_Value
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &RegexpSituationParameterValueResource{}
var _ resource.ResourceWithImportState = &RegexpSituationParameterValueResource{}
var _ context.Context = context.Background()


// RegexpSituationParameterValueResource defines the resource implementation.
type RegexpSituationParameterValueResource struct {
    ResourceBase[RegexpSituationParameterValueResourceModel]
}


// Schema defines the schema for the RegexpSituationParameterValue resource.
func (r *RegexpSituationParameterValueResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a regular expression parameter value within a situation, allowing for the application of specific regular expressions to the situation's parameters.",
      Attributes: GetRegexpSituationParameterValueSchemaAttributes(ctx),
      Blocks: GetRegexpSituationParameterValueSchemaBlocks(ctx),
    } // schema
    

}

// NewRegexpSituationParameterValueResource creates a new instance of the RegexpSituationParameterValue resource.
func NewRegexpSituationParameterValueResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing RegexpSituationParameterValue resource")
	r := &RegexpSituationParameterValueResource{
        ResourceBase: ResourceBase[RegexpSituationParameterValueResourceModel]{
             resourceType: "reg_exp_situation_parameter_value",
             isSubResource: true,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}