// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Integer_Situation_Parameter_Value
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &IntegerSituationParameterValueResource{}
var _ resource.ResourceWithImportState = &IntegerSituationParameterValueResource{}
var _ context.Context = context.Background()


// IntegerSituationParameterValueResource defines the resource implementation.
type IntegerSituationParameterValueResource struct {
    ResourceBase[IntegerSituationParameterValueResourceModel]
}


// Schema defines the schema for the IntegerSituationParameterValue resource.
func (r *IntegerSituationParameterValueResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an integer parameter value within a situation, allowing for the application of specific integer values to the situation's parameters.",
      Attributes: GetIntegerSituationParameterValueSchemaAttributes(ctx),
      Blocks: GetIntegerSituationParameterValueSchemaBlocks(ctx),
    } // schema
    

}

// NewIntegerSituationParameterValueResource creates a new instance of the IntegerSituationParameterValue resource.
func NewIntegerSituationParameterValueResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing IntegerSituationParameterValue resource")
	r := &IntegerSituationParameterValueResource{
        ResourceBase: ResourceBase[IntegerSituationParameterValueResourceModel]{
             resourceType: "integer_situation_parameter_value",
             isSubResource: true,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}