// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Application_Situation_Context
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ApplicationSituationContextResource{}
var _ resource.ResourceWithImportState = &ApplicationSituationContextResource{}
var _ context.Context = context.Background()


// ApplicationSituationContextResource defines the resource implementation.
type ApplicationSituationContextResource struct {
    ResourceBase[ApplicationSituationContextResourceModel]
}


// Schema defines the schema for the ApplicationSituationContext resource.
func (r *ApplicationSituationContextResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an Application Situation context. It can contain other groups or individual situation contexts.",
      Attributes: GetApplicationSituationContextSchemaAttributes(ctx),
      Blocks: GetApplicationSituationContextSchemaBlocks(ctx),
    } // schema
    

}

// NewApplicationSituationContextResource creates a new instance of the ApplicationSituationContext resource.
func NewApplicationSituationContextResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ApplicationSituationContext resource")
	r := &ApplicationSituationContextResource{
        ResourceBase: ResourceBase[ApplicationSituationContextResourceModel]{
             resourceType: "application_situation_context",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}