// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Administration_Domain
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AdministrationDomainResource{}
var _ resource.ResourceWithImportState = &AdministrationDomainResource{}
var _ context.Context = context.Background()

// AdministrationDomainResource defines the resource implementation.
type AdministrationDomainResource struct {
	ResourceBase[AdministrationDomainResourceModel]
}

// Schema defines the schema for the AdministrationDomain resource.
func (r *AdministrationDomainResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(PROVIDER_NAME + "_" + r.resourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
		Attributes:  GetAdministrationDomainSchemaAttributes(ctx),
		Blocks:      GetAdministrationDomainSchemaBlocks(ctx),
	} // schema

}

// NewAdministrationDomainResource creates a new instance of the AdministrationDomain resource.
func NewAdministrationDomainResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing AdministrationDomain resource")
	r := &AdministrationDomainResource{
		ResourceBase: ResourceBase[AdministrationDomainResourceModel]{
			resourceType:  "admin_domain",
			isSubResource: false,
		},
	}
	r.ResourceBase.dispatch = r
	return r
}
