// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: API_Client
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ApiClientResource{}
var _ resource.ResourceWithImportState = &ApiClientResource{}
var _ context.Context = context.Background()


// ApiClientResource defines the resource implementation.
type ApiClientResource struct {
    ResourceBase[ApiClientResourceModel]
}


// Schema defines the schema for the ApiClient resource.
func (r *ApiClientResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a API Client. It is an element that defines the details of a single person that is allowed to log on to Management Server through REST services.",
      Attributes: GetApiClientSchemaAttributes(ctx),
      Blocks: GetApiClientSchemaBlocks(ctx),
    } // schema
    

}

// NewApiClientResource creates a new instance of the ApiClient resource.
func NewApiClientResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ApiClient resource")
	r := &ApiClientResource{
        ResourceBase: ResourceBase[ApiClientResourceModel]{
             resourceType: "api_user",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}