// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: TCP_Service_Group
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &TcpServiceGroupResource{}
var _ resource.ResourceWithImportState = &TcpServiceGroupResource{}
var _ context.Context = context.Background()


// TcpServiceGroupResource defines the resource implementation.
type TcpServiceGroupResource struct {
    ResourceBase[TcpServiceGroupResourceModel]
}


// Schema defines the schema for the TcpServiceGroup resource.
func (r *TcpServiceGroupResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a TCP Service Group, which is used to group a list of TCP Services. It can contain both individual TCP Services and other Service Groups.",
      Attributes: GetTcpServiceGroupSchemaAttributes(ctx),
      Blocks: GetTcpServiceGroupSchemaBlocks(ctx),
    } // schema
    

}

// NewTcpServiceGroupResource creates a new instance of the TcpServiceGroup resource.
func NewTcpServiceGroupResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing TcpServiceGroup resource")
	r := &TcpServiceGroupResource{
        ResourceBase: ResourceBase[TcpServiceGroupResourceModel]{
             resourceType: "tcp_service_group",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}