// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: SSL_VPN_Zip_File
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &SslVpnZipFileResource{}
var _ resource.ResourceWithImportState = &SslVpnZipFileResource{}
var _ context.Context = context.Background()


// SslVpnZipFileResource defines the resource implementation.
type SslVpnZipFileResource struct {
    ResourceBase[SslVpnZipFileResourceModel]
}


// Schema defines the schema for the SslVpnZipFile resource.
func (r *SslVpnZipFileResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This is a SSL VPN Zip File. It represents a zip file used in the SSL VPN context, typically containing configuration or other related files.",
      Attributes: GetSslVpnZipFileSchemaAttributes(ctx),
      Blocks: GetSslVpnZipFileSchemaBlocks(ctx),
    } // schema
    

}

// NewSslVpnZipFileResource creates a new instance of the SslVpnZipFile resource.
func NewSslVpnZipFileResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing SslVpnZipFile resource")
	r := &SslVpnZipFileResource{
        ResourceBase: ResourceBase[SslVpnZipFileResourceModel]{
             resourceType: "ssl_vpn_zip_file",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}