// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: VPN_Site
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VpnSiteResource{}
var _ resource.ResourceWithImportState = &VpnSiteResource{}
var _ context.Context = context.Background()

// VpnSiteResource defines the resource implementation.
type VpnSiteResource struct {
	ResourceBase[VpnSiteResourceModel]
}

// Schema defines the schema for the VpnSite resource.
func (r *VpnSiteResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(PROVIDER_NAME + "_" + r.resourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a VPN Site, which is a collection of network elements that are part of a VPN. It can be associated with a gateway and has references to VPNs.",
		Attributes:  GetVpnSiteSchemaAttributes(ctx),
		Blocks:      GetVpnSiteSchemaBlocks(ctx),
	} // schema

}

// NewVpnSiteResource creates a new instance of the VpnSite resource.
func NewVpnSiteResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VpnSite resource")
	r := &VpnSiteResource{
		ResourceBase: ResourceBase[VpnSiteResourceModel]{
			resourceType:  "vpn_site",
			isSubResource: true,
		},
	}
	r.ResourceBase.dispatch = r
	return r
}
