// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: BGP_Peering
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &BgpPeeringResource{}
var _ resource.ResourceWithImportState = &BgpPeeringResource{}
var _ context.Context = context.Background()


// BgpPeeringResource defines the resource implementation.
type BgpPeeringResource struct {
    ResourceBase[BgpPeeringResourceModel]
}


// Schema defines the schema for the BgpPeering resource.
func (r *BgpPeeringResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents the BGP Peering for Dynamic Routing Firewall functionality.",
      Attributes: GetBgpPeeringSchemaAttributes(ctx),
      Blocks: GetBgpPeeringSchemaBlocks(ctx),
    } // schema
    

}

// NewBgpPeeringResource creates a new instance of the BgpPeering resource.
func NewBgpPeeringResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing BgpPeering resource")
	r := &BgpPeeringResource{
        ResourceBase: ResourceBase[BgpPeeringResourceModel]{
             resourceType: "bgp_peering",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}