// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Broker_Domain_Config_File
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &BrokerDomainConfigFileResource{}
var _ resource.ResourceWithImportState = &BrokerDomainConfigFileResource{}
var _ context.Context = context.Background()


// BrokerDomainConfigFileResource defines the resource implementation.
type BrokerDomainConfigFileResource struct {
    ResourceBase[BrokerDomainConfigFileResourceModel]
}


// Schema defines the schema for the BrokerDomainConfigFile resource.
func (r *BrokerDomainConfigFileResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This is a configuration file for the VPN Broker Domain. It contains settings and configurations specific to the broker domain, used for managing VPN connections and policies.",
      Attributes: GetBrokerDomainConfigFileSchemaAttributes(ctx),
      Blocks: GetBrokerDomainConfigFileSchemaBlocks(ctx),
    } // schema
    

}

// NewBrokerDomainConfigFileResource creates a new instance of the BrokerDomainConfigFile resource.
func NewBrokerDomainConfigFileResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing BrokerDomainConfigFile resource")
	r := &BrokerDomainConfigFileResource{
        ResourceBase: ResourceBase[BrokerDomainConfigFileResourceModel]{
             resourceType: "broker_config_file",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}