// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Inspection_Situation
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &InspectionSituationResource{}
var _ resource.ResourceWithImportState = &InspectionSituationResource{}
var _ context.Context = context.Background()


// InspectionSituationResource defines the resource implementation.
type InspectionSituationResource struct {
    ResourceBase[InspectionSituationResourceModel]
}


// Schema defines the schema for the InspectionSituation resource.
func (r *InspectionSituationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an Inspection Situation, which is used to identify and describe detected events in the traffic or in the operation of the system.",
      Attributes: GetInspectionSituationSchemaAttributes(ctx),
      Blocks: GetInspectionSituationSchemaBlocks(ctx),
    } // schema
    

}

// NewInspectionSituationResource creates a new instance of the InspectionSituation resource.
func NewInspectionSituationResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing InspectionSituation resource")
	r := &InspectionSituationResource{
        ResourceBase: ResourceBase[InspectionSituationResourceModel]{
             resourceType: "inspection_situation",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}