// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: ECA_Application_Category_Tag
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &EcaApplicationCategoryTagResource{}
var _ resource.ResourceWithImportState = &EcaApplicationCategoryTagResource{}
var _ context.Context = context.Background()


// EcaApplicationCategoryTagResource defines the resource implementation.
type EcaApplicationCategoryTagResource struct {
    ResourceBase[EcaApplicationCategoryTagResourceModel]
}


// Schema defines the schema for the EcaApplicationCategoryTag resource.
func (r *EcaApplicationCategoryTagResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an ECA Application Category Tag, which is used to categorize elements based on their application category. It is a type of tag that can be applied to various elements in the system to indicate their application category classification.",
      Attributes: GetEcaApplicationCategoryTagSchemaAttributes(ctx),
      Blocks: GetEcaApplicationCategoryTagSchemaBlocks(ctx),
    } // schema
    

}

// NewEcaApplicationCategoryTagResource creates a new instance of the EcaApplicationCategoryTag resource.
func NewEcaApplicationCategoryTagResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing EcaApplicationCategoryTag resource")
	r := &EcaApplicationCategoryTagResource{
        ResourceBase: ResourceBase[EcaApplicationCategoryTagResourceModel]{
             resourceType: "eia_application_category_tag",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}