// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: File_Filtering_Policy
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &FileFilteringPolicyResource{}
var _ resource.ResourceWithImportState = &FileFilteringPolicyResource{}
var _ context.Context = context.Background()


// FileFilteringPolicyResource defines the resource implementation.
type FileFilteringPolicyResource struct {
    ResourceBase[FileFilteringPolicyResourceModel]
}


// Schema defines the schema for the FileFilteringPolicy resource.
func (r *FileFilteringPolicyResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a File Filtering Policy, which is used to define the action and inspection rules for File Filtering Engines.",
      Attributes: GetFileFilteringPolicySchemaAttributes(ctx),
      Blocks: GetFileFilteringPolicySchemaBlocks(ctx),
    } // schema
    

}

// NewFileFilteringPolicyResource creates a new instance of the FileFilteringPolicy resource.
func NewFileFilteringPolicyResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing FileFilteringPolicy resource")
	r := &FileFilteringPolicyResource{
        ResourceBase: ResourceBase[FileFilteringPolicyResourceModel]{
             resourceType: "file_filtering_policy",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}