// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Sandbox_Data_Center
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &SandboxDataCenterResource{}
var _ resource.ResourceWithImportState = &SandboxDataCenterResource{}
var _ context.Context = context.Background()


// SandboxDataCenterResource defines the resource implementation.
type SandboxDataCenterResource struct {
    ResourceBase[SandboxDataCenterResourceModel]
}


// Schema defines the schema for the SandboxDataCenter resource.
func (r *SandboxDataCenterResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a Sandbox Data Center element, which is referenced by the sandbox service. It contains information about the sandbox's hostname, server URL, portal URL, API URL, API key, type, and TLS profile.",
      Attributes: GetSandboxDataCenterSchemaAttributes(ctx),
      Blocks: GetSandboxDataCenterSchemaBlocks(ctx),
    } // schema
    

}

// NewSandboxDataCenterResource creates a new instance of the SandboxDataCenter resource.
func NewSandboxDataCenterResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing SandboxDataCenter resource")
	r := &SandboxDataCenterResource{
        ResourceBase: ResourceBase[SandboxDataCenterResourceModel]{
             resourceType: "sandbox_data_center",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}