// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Certificate_Renewal_System_Task
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &CertificateRenewalSystemTaskResource{}
var _ resource.ResourceWithImportState = &CertificateRenewalSystemTaskResource{}
var _ context.Context = context.Background()


// CertificateRenewalSystemTaskResource defines the resource implementation.
type CertificateRenewalSystemTaskResource struct {
    ResourceBase[CertificateRenewalSystemTaskResourceModel]
}


// Schema defines the schema for the CertificateRenewalSystemTask resource.
func (r *CertificateRenewalSystemTaskResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a Certificate Renewal System Task, which is used to renew gateway certificates in the system. It is a type of system task that can be scheduled and executed to ensure that the gateway certificates are up-to-date.",
      Attributes: GetCertificateRenewalSystemTaskSchemaAttributes(ctx),
      Blocks: GetCertificateRenewalSystemTaskSchemaBlocks(ctx),
    } // schema
    

}

// NewCertificateRenewalSystemTaskResource creates a new instance of the CertificateRenewalSystemTask resource.
func NewCertificateRenewalSystemTaskResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing CertificateRenewalSystemTask resource")
	r := &CertificateRenewalSystemTaskResource{
        ResourceBase: ResourceBase[CertificateRenewalSystemTaskResourceModel]{
             resourceType: "renew_gw_certificates_task",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}