// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Archive_Log_Task
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ArchiveLogTaskResource{}
var _ resource.ResourceWithImportState = &ArchiveLogTaskResource{}
var _ context.Context = context.Background()


// ArchiveLogTaskResource defines the resource implementation.
type ArchiveLogTaskResource struct {
    ResourceBase[ArchiveLogTaskResourceModel]
}


// Schema defines the schema for the ArchiveLogTask resource.
func (r *ArchiveLogTaskResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an Archive Log Task, which is used to archive logs in the system. It is a type of log task that can be scheduled and executed to ensure that logs are archived properly.",
      Attributes: GetArchiveLogTaskSchemaAttributes(ctx),
      Blocks: GetArchiveLogTaskSchemaBlocks(ctx),
    } // schema
    

}

// NewArchiveLogTaskResource creates a new instance of the ArchiveLogTask resource.
func NewArchiveLogTaskResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ArchiveLogTask resource")
	r := &ArchiveLogTaskResource{
        ResourceBase: ResourceBase[ArchiveLogTaskResourceModel]{
             resourceType: "archive_log_task",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}