// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Connection_Type
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ConnectionTypeResource{}
var _ resource.ResourceWithImportState = &ConnectionTypeResource{}
var _ context.Context = context.Background()


// ConnectionTypeResource defines the resource implementation.
type ConnectionTypeResource struct {
    ResourceBase[ConnectionTypeResourceModel]
}


// Schema defines the schema for the ConnectionType resource.
func (r *ConnectionTypeResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a connection type used in endpoints, which defines the connectivity group, mode, and link type for VPN connections.",
      Attributes: GetConnectionTypeSchemaAttributes(ctx),
      Blocks: GetConnectionTypeSchemaBlocks(ctx),
    } // schema
    

}

// NewConnectionTypeResource creates a new instance of the ConnectionType resource.
func NewConnectionTypeResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ConnectionType resource")
	r := &ConnectionTypeResource{
        ResourceBase: ResourceBase[ConnectionTypeResourceModel]{
             resourceType: "connection_type",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}