// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Virtual_Layer2
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VirtualLayer2Resource{}
var _ resource.ResourceWithImportState = &VirtualLayer2Resource{}
var _ context.Context = context.Background()

// VirtualLayer2Resource defines the resource implementation.
type VirtualLayer2Resource struct {
	ResourceBase[VirtualLayer2ResourceModel]
}

// Schema defines the schema for the VirtualLayer2 resource.
func (r *VirtualLayer2Resource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(PROVIDER_NAME + "_" + r.resourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Virtual Layer 2 Firewall, a logically-separate engine that runs as virtual layer 2 firewall instance on a Master NGFW Engine.",
		Attributes:  GetVirtualLayer2SchemaAttributes(ctx),
		Blocks:      GetVirtualLayer2SchemaBlocks(ctx),
	} // schema

}

// NewVirtualLayer2Resource creates a new instance of the VirtualLayer2 resource.
func NewVirtualLayer2Resource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VirtualLayer2 resource")
	r := &VirtualLayer2Resource{
		ResourceBase: ResourceBase[VirtualLayer2ResourceModel]{
			resourceType:  "virtual_firewall_layer2",
			isSubResource: false,
		},
	}
	r.ResourceBase.dispatch = r
	return r
}
