// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Hardware_Tag
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &HardwareTagResource{}
var _ resource.ResourceWithImportState = &HardwareTagResource{}
var _ context.Context = context.Background()


// HardwareTagResource defines the resource implementation.
type HardwareTagResource struct {
    ResourceBase[HardwareTagResourceModel]
}


// Schema defines the schema for the HardwareTag resource.
func (r *HardwareTagResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a Hardware Tag, which is used to categorize elements based on their hardware type. It is a type of tag that can be applied to various elements in the system to indicate their hardware classification.",
      Attributes: GetHardwareTagSchemaAttributes(ctx),
      Blocks: GetHardwareTagSchemaBlocks(ctx),
    } // schema
    

}

// NewHardwareTagResource creates a new instance of the HardwareTag resource.
func NewHardwareTagResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing HardwareTag resource")
	r := &HardwareTagResource{
        ResourceBase: ResourceBase[HardwareTagResourceModel]{
             resourceType: "hardware_tag",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}