// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Virtual_Physical_Interface
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VirtualPhysicalInterfaceResource{}
var _ resource.ResourceWithImportState = &VirtualPhysicalInterfaceResource{}
var _ context.Context = context.Background()


// VirtualPhysicalInterfaceResource defines the resource implementation.
type VirtualPhysicalInterfaceResource struct {
    ResourceBase[VirtualPhysicalInterfaceResourceModel]
}


// Schema defines the schema for the VirtualPhysicalInterface resource.
func (r *VirtualPhysicalInterfaceResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a virtual physical interface for the Virtual Firewall, Virtual Firewall Layer 2, and Virtual IPS.",
      Attributes: GetVirtualPhysicalInterfaceSchemaAttributes(ctx),
      Blocks: GetVirtualPhysicalInterfaceSchemaBlocks(ctx),
    } // schema
    

}

// NewVirtualPhysicalInterfaceResource creates a new instance of the VirtualPhysicalInterface resource.
func NewVirtualPhysicalInterfaceResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VirtualPhysicalInterface resource")
	r := &VirtualPhysicalInterfaceResource{
        ResourceBase: ResourceBase[VirtualPhysicalInterfaceResourceModel]{
             resourceType: "virtual_physical_interface",
             isSubResource: true,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}