// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: URL_List_Application_Situation
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &UrlListApplicationSituationResource{}
var _ resource.ResourceWithImportState = &UrlListApplicationSituationResource{}
var _ context.Context = context.Background()


// UrlListApplicationSituationResource defines the resource implementation.
type UrlListApplicationSituationResource struct {
    ResourceBase[UrlListApplicationSituationResourceModel]
}


// Schema defines the schema for the UrlListApplicationSituation resource.
func (r *UrlListApplicationSituationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a URL List Application Situation, which is used for URL list filtering in URL filtering.",
      Attributes: GetUrlListApplicationSituationSchemaAttributes(ctx),
      Blocks: GetUrlListApplicationSituationSchemaBlocks(ctx),
    } // schema
    

}

// NewUrlListApplicationSituationResource creates a new instance of the UrlListApplicationSituation resource.
func NewUrlListApplicationSituationResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing UrlListApplicationSituation resource")
	r := &UrlListApplicationSituationResource{
        ResourceBase: ResourceBase[UrlListApplicationSituationResourceModel]{
             resourceType: "url_list_application",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}