// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Route_Map_Policy
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &RouteMapPolicyResource{}
var _ resource.ResourceWithImportState = &RouteMapPolicyResource{}
var _ context.Context = context.Background()


// RouteMapPolicyResource defines the resource implementation.
type RouteMapPolicyResource struct {
    ResourceBase[RouteMapPolicyResourceModel]
}


// Schema defines the schema for the RouteMapPolicy resource.
func (r *RouteMapPolicyResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a Route Map Policy for the Dynamic Routing Firewall settings, which is used to control the routing behavior based on specific rules.",
      Attributes: GetRouteMapPolicySchemaAttributes(ctx),
      Blocks: GetRouteMapPolicySchemaBlocks(ctx),
    } // schema
    

}

// NewRouteMapPolicyResource creates a new instance of the RouteMapPolicy resource.
func NewRouteMapPolicyResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing RouteMapPolicy resource")
	r := &RouteMapPolicyResource{
        ResourceBase: ResourceBase[RouteMapPolicyResourceModel]{
             resourceType: "route_map",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}