// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: User_Alert_Check
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &UserAlertCheckResource{}
var _ resource.ResourceWithImportState = &UserAlertCheckResource{}
var _ context.Context = context.Background()


// UserAlertCheckResource defines the resource implementation.
type UserAlertCheckResource struct {
    ResourceBase[UserAlertCheckResourceModel]
}


// Schema defines the schema for the UserAlertCheck resource.
func (r *UserAlertCheckResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a User Alert Check. It contains settings for the type of check, threshold values, filter, and associated alert.",
      Attributes: GetUserAlertCheckSchemaAttributes(ctx),
      Blocks: GetUserAlertCheckSchemaBlocks(ctx),
    } // schema
    

}

// NewUserAlertCheckResource creates a new instance of the UserAlertCheck resource.
func NewUserAlertCheckResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing UserAlertCheck resource")
	r := &UserAlertCheckResource{
        ResourceBase: ResourceBase[UserAlertCheckResourceModel]{
             resourceType: "user_alert_check",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}