// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Internal_File
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &InternalFileResource{}
var _ resource.ResourceWithImportState = &InternalFileResource{}
var _ context.Context = context.Background()

// InternalFileResource defines the resource implementation.
type InternalFileResource struct {
	ResourceBase[InternalFileResourceModel]
}

// Schema defines the schema for the InternalFile resource.
func (r *InternalFileResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(PROVIDER_NAME + "_" + r.resourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This is an Internal File. It represents a file used internally within the system, typically for configuration or other internal purposes.",
		Attributes:  GetInternalFileSchemaAttributes(ctx),
		Blocks:      GetInternalFileSchemaBlocks(ctx),
	} // schema

}

// NewInternalFileResource creates a new instance of the InternalFile resource.
func NewInternalFileResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing InternalFile resource")
	r := &InternalFileResource{
		ResourceBase: ResourceBase[InternalFileResourceModel]{
			resourceType:  "internal_file",
			isSubResource: false,
		},
	}
	r.ResourceBase.dispatch = r
	return r
}
