// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Country_IP_List_Group_Tag
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &CountryIpListGroupTagResource{}
var _ resource.ResourceWithImportState = &CountryIpListGroupTagResource{}
var _ context.Context = context.Background()


// CountryIpListGroupTagResource defines the resource implementation.
type CountryIpListGroupTagResource struct {
    ResourceBase[CountryIpListGroupTagResourceModel]
}


// Schema defines the schema for the CountryIpListGroupTag resource.
func (r *CountryIpListGroupTagResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a Country IP List Group Tag, which is used to categorize elements based on their association with specific countries. It is a type of tag that can be applied to various elements in the system to indicate their country classification.",
      Attributes: GetCountryIpListGroupTagSchemaAttributes(ctx),
      Blocks: GetCountryIpListGroupTagSchemaBlocks(ctx),
    } // schema
    

}

// NewCountryIpListGroupTagResource creates a new instance of the CountryIpListGroupTag resource.
func NewCountryIpListGroupTagResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing CountryIpListGroupTag resource")
	r := &CountryIpListGroupTagResource{
        ResourceBase: ResourceBase[CountryIpListGroupTagResourceModel]{
             resourceType: "ip_country_group",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}