// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Gateway_Settings
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &GatewaySettingsResource{}
var _ resource.ResourceWithImportState = &GatewaySettingsResource{}
var _ context.Context = context.Background()


// GatewaySettingsResource defines the resource implementation.
type GatewaySettingsResource struct {
    ResourceBase[GatewaySettingsResourceModel]
}


// Schema defines the schema for the GatewaySettings resource.
func (r *GatewaySettingsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents various gateway and VPN parameters to be set at Firewall level. These settings are used for the negotiation of VPN connections.",
      Attributes: GetGatewaySettingsSchemaAttributes(ctx),
      Blocks: GetGatewaySettingsSchemaBlocks(ctx),
    } // schema
    

}

// NewGatewaySettingsResource creates a new instance of the GatewaySettings resource.
func NewGatewaySettingsResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing GatewaySettings resource")
	r := &GatewaySettingsResource{
        ResourceBase: ResourceBase[GatewaySettingsResourceModel]{
             resourceType: "gateway_settings",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}