// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: VPN_Profile
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VpnProfileResource{}
var _ resource.ResourceWithImportState = &VpnProfileResource{}
var _ context.Context = context.Background()


// VpnProfileResource defines the resource implementation.
type VpnProfileResource struct {
    ResourceBase[VpnProfileResourceModel]
}


// Schema defines the schema for the VpnProfile resource.
func (r *VpnProfileResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a VPN Profile. It contains settings for IKE and IPsec lifetimes, keep-alive options, certificate authorities, and authentication methods.",
      Attributes: GetVpnProfileSchemaAttributes(ctx),
      Blocks: GetVpnProfileSchemaBlocks(ctx),
    } // schema
    

}

// NewVpnProfileResource creates a new instance of the VpnProfile resource.
func NewVpnProfileResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VpnProfile resource")
	r := &VpnProfileResource{
        ResourceBase: ResourceBase[VpnProfileResourceModel]{
             resourceType: "vpn_profile",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}