// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: L2FW_Interface_IPv6_Access_Rule
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &L2fwInterfaceIpv6AccessRuleResource{}
var _ resource.ResourceWithImportState = &L2fwInterfaceIpv6AccessRuleResource{}
var _ context.Context = context.Background()


// L2fwInterfaceIpv6AccessRuleResource defines the resource implementation.
type L2fwInterfaceIpv6AccessRuleResource struct {
    ResourceBase[L2fwInterfaceIpv6AccessRuleResourceModel]
}


// Schema defines the schema for the L2fwInterfaceIpv6AccessRule resource.
func (r *L2fwInterfaceIpv6AccessRuleResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a L2FW Interface IPv6 Access Rule. It defines how one type of IPv6 connection is handled by providing matching criteria based on the source, destination, and protocol information.",
      Attributes: GetL2fwInterfaceIpv6AccessRuleSchemaAttributes(ctx),
      Blocks: GetL2fwInterfaceIpv6AccessRuleSchemaBlocks(ctx),
    } // schema
    

}

// NewL2fwInterfaceIpv6AccessRuleResource creates a new instance of the L2fwInterfaceIpv6AccessRule resource.
func NewL2fwInterfaceIpv6AccessRuleResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing L2fwInterfaceIpv6AccessRule resource")
	r := &L2fwInterfaceIpv6AccessRuleResource{
        ResourceBase: ResourceBase[L2fwInterfaceIpv6AccessRuleResourceModel]{
             resourceType: "l2_interface_ipv6_access_rule",
             isSubResource: true,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}
// special case for rank attribute
    func (r *L2fwInterfaceIpv6AccessRuleResource) getCreateRequestParams(_ context.Context, data *L2fwInterfaceIpv6AccessRuleResourceModel) (map[string]string, error) {
  	if !data.Rank.IsNull() && !data.Rank.IsUnknown() {
        queryParams := map[string]string{
           "keep_specified_rank": "true",
        }
        return queryParams, nil
    }
    return nil, nil
}