// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Specific_Software_Tag
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &SpecificSoftwareTagResource{}
var _ resource.ResourceWithImportState = &SpecificSoftwareTagResource{}
var _ context.Context = context.Background()


// SpecificSoftwareTagResource defines the resource implementation.
type SpecificSoftwareTagResource struct {
    ResourceBase[SpecificSoftwareTagResourceModel]
}


// Schema defines the schema for the SpecificSoftwareTag resource.
func (r *SpecificSoftwareTagResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a Specific Software Tag, which is used to categorize elements based on specific software. It is a type of tag that can be applied to various elements in the system to indicate their association with specific software.",
      Attributes: GetSpecificSoftwareTagSchemaAttributes(ctx),
      Blocks: GetSpecificSoftwareTagSchemaBlocks(ctx),
    } // schema
    

}

// NewSpecificSoftwareTagResource creates a new instance of the SpecificSoftwareTag resource.
func NewSpecificSoftwareTagResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing SpecificSoftwareTag resource")
	r := &SpecificSoftwareTagResource{
        ResourceBase: ResourceBase[SpecificSoftwareTagResourceModel]{
             resourceType: "application_specific_tag",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}