// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: External_DNS_Server
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ExternalDnsServerResource{}
var _ resource.ResourceWithImportState = &ExternalDnsServerResource{}
var _ context.Context = context.Background()


// ExternalDnsServerResource defines the resource implementation.
type ExternalDnsServerResource struct {
    ResourceBase[ExternalDnsServerResourceModel]
}


// Schema defines the schema for the ExternalDnsServer resource.
func (r *ExternalDnsServerResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an External DNS (Domain Name Service) Server, which is used for DDNS updates, resolving virus signature mirrors, and URL filtering categorization services.",
      Attributes: GetExternalDnsServerSchemaAttributes(ctx),
      Blocks: GetExternalDnsServerSchemaBlocks(ctx),
    } // schema
    

}

// NewExternalDnsServerResource creates a new instance of the ExternalDnsServer resource.
func NewExternalDnsServerResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ExternalDnsServer resource")
	r := &ExternalDnsServerResource{
        ResourceBase: ResourceBase[ExternalDnsServerResourceModel]{
             resourceType: "dns_server",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}