// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Master_Engine
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &MasterEngineResource{}
var _ resource.ResourceWithImportState = &MasterEngineResource{}
var _ context.Context = context.Background()


// MasterEngineResource defines the resource implementation.
type MasterEngineResource struct {
    ResourceBase[MasterEngineResourceModel]
}


// Schema defines the schema for the MasterEngine resource.
func (r *MasterEngineResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a physical engine device that provides resources for Virtual Security Engines. One physical Master NGFW Engine can support multiple Virtual NGFW Engines.",
      Attributes: GetMasterEngineSchemaAttributes(ctx),
      Blocks: GetMasterEngineSchemaBlocks(ctx),
    } // schema
    

}

// NewMasterEngineResource creates a new instance of the MasterEngine resource.
func NewMasterEngineResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing MasterEngine resource")
	r := &MasterEngineResource{
        ResourceBase: ResourceBase[MasterEngineResourceModel]{
             resourceType: "master_engine",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}