// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: SSL_VPN_Logon_Page_Background
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &SslVpnLogonPageBackgroundResource{}
var _ resource.ResourceWithImportState = &SslVpnLogonPageBackgroundResource{}
var _ context.Context = context.Background()


// SslVpnLogonPageBackgroundResource defines the resource implementation.
type SslVpnLogonPageBackgroundResource struct {
    ResourceBase[SslVpnLogonPageBackgroundResourceModel]
}


// Schema defines the schema for the SslVpnLogonPageBackground resource.
func (r *SslVpnLogonPageBackgroundResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This is an Application Access Logon page background. It represents a background image used in the Application Access logon page, typically for visual customization.",
      Attributes: GetSslVpnLogonPageBackgroundSchemaAttributes(ctx),
      Blocks: GetSslVpnLogonPageBackgroundSchemaBlocks(ctx),
    } // schema
    

}

// NewSslVpnLogonPageBackgroundResource creates a new instance of the SslVpnLogonPageBackground resource.
func NewSslVpnLogonPageBackgroundResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing SslVpnLogonPageBackground resource")
	r := &SslVpnLogonPageBackgroundResource{
        ResourceBase: ResourceBase[SslVpnLogonPageBackgroundResourceModel]{
             resourceType: "ssl_vpn_logon_page_background",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}