// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Address_Range
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AddressRangeResource{}
var _ resource.ResourceWithImportState = &AddressRangeResource{}
var _ context.Context = context.Background()


// AddressRangeResource defines the resource implementation.
type AddressRangeResource struct {
    ResourceBase[AddressRangeResourceModel]
}


// Schema defines the schema for the AddressRange resource.
func (r *AddressRangeResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an Address Range, which is a Network Element that defines a range of IP addresses. It includes attributes for the range of IP addresses, which must be valid IPv4 or IPv6 addresses.",
      Attributes: GetAddressRangeSchemaAttributes(ctx),
      Blocks: GetAddressRangeSchemaBlocks(ctx),
    } // schema
    

}

// NewAddressRangeResource creates a new instance of the AddressRange resource.
func NewAddressRangeResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing AddressRange resource")
	r := &AddressRangeResource{
        ResourceBase: ResourceBase[AddressRangeResourceModel]{
             resourceType: "address_range",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}