// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: IPS_Policy
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &IpsPolicyResource{}
var _ resource.ResourceWithImportState = &IpsPolicyResource{}
var _ context.Context = context.Background()


// IpsPolicyResource defines the resource implementation.
type IpsPolicyResource struct {
    ResourceBase[IpsPolicyResourceModel]
}


// Schema defines the schema for the IpsPolicy resource.
func (r *IpsPolicyResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents an IPS Policy, which is used to define the action and inspection rules for IPS Engines.",
      Attributes: GetIpsPolicySchemaAttributes(ctx),
      Blocks: GetIpsPolicySchemaBlocks(ctx),
    } // schema
    

}

// NewIpsPolicyResource creates a new instance of the IpsPolicy resource.
func NewIpsPolicyResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing IpsPolicy resource")
	r := &IpsPolicyResource{
        ResourceBase: ResourceBase[IpsPolicyResourceModel]{
             resourceType: "ips_policy",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}