// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: External_BGP_Peer
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ExternalBgpPeerResource{}
var _ resource.ResourceWithImportState = &ExternalBgpPeerResource{}
var _ context.Context = context.Background()


// ExternalBgpPeerResource defines the resource implementation.
type ExternalBgpPeerResource struct {
    ResourceBase[ExternalBgpPeerResourceModel]
}


// Schema defines the schema for the ExternalBgpPeer resource.
func (r *ExternalBgpPeerResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents the External BGP Peer for Dynamic Routing Firewall functionality. It is used to configure external BGP peers in the firewall's dynamic routing capabilities.",
      Attributes: GetExternalBgpPeerSchemaAttributes(ctx),
      Blocks: GetExternalBgpPeerSchemaBlocks(ctx),
    } // schema
    

}

// NewExternalBgpPeerResource creates a new instance of the ExternalBgpPeer resource.
func NewExternalBgpPeerResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ExternalBgpPeer resource")
	r := &ExternalBgpPeerResource{
        ResourceBase: ResourceBase[ExternalBgpPeerResourceModel]{
             resourceType: "external_bgp_peer",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}