// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Inspected_Service
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &InspectedServiceResource{}
var _ resource.ResourceWithImportState = &InspectedServiceResource{}
var _ context.Context = context.Background()


// InspectedServiceResource defines the resource implementation.
type InspectedServiceResource struct {
    ResourceBase[InspectedServiceResourceModel]
}


// Schema defines the schema for the InspectedService resource.
func (r *InspectedServiceResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a sub part of a Proxy Server, defining the protocol to be inspected and the port number used for inspection.",
      Attributes: GetInspectedServiceSchemaAttributes(ctx),
      Blocks: GetInspectedServiceSchemaBlocks(ctx),
    } // schema
    

}

// NewInspectedServiceResource creates a new instance of the InspectedService resource.
func NewInspectedServiceResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing InspectedService resource")
	r := &InspectedServiceResource{
        ResourceBase: ResourceBase[InspectedServiceResourceModel]{
             resourceType: "inspected_service",
             isSubResource: true,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}