// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: UDP_Service_Group
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &UdpServiceGroupResource{}
var _ resource.ResourceWithImportState = &UdpServiceGroupResource{}
var _ context.Context = context.Background()

// UdpServiceGroupResource defines the resource implementation.
type UdpServiceGroupResource struct {
	ResourceBase[UdpServiceGroupResourceModel]
}

// Schema defines the schema for the UdpServiceGroup resource.
func (r *UdpServiceGroupResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(PROVIDER_NAME + "_" + r.resourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a UDP Service Group, which is used to group a list of UDP Services. It can contain both individual UDP Services and other Service Groups.",
		Attributes:  GetUdpServiceGroupSchemaAttributes(ctx),
		Blocks:      GetUdpServiceGroupSchemaBlocks(ctx),
	} // schema

}

// NewUdpServiceGroupResource creates a new instance of the UdpServiceGroup resource.
func NewUdpServiceGroupResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing UdpServiceGroup resource")
	r := &UdpServiceGroupResource{
		ResourceBase: ResourceBase[UdpServiceGroupResourceModel]{
			resourceType:  "udp_service_group",
			isSubResource: false,
		},
	}
	r.ResourceBase.dispatch = r
	return r
}
