// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Inspection_Global_Rule
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &InspectionGlobalRuleResource{}
var _ resource.ResourceWithImportState = &InspectionGlobalRuleResource{}
var _ context.Context = context.Background()

// InspectionGlobalRuleResource defines the resource implementation.
type InspectionGlobalRuleResource struct {
	ResourceBase[InspectionGlobalRuleResourceModel]
}

// Schema defines the schema for the InspectionGlobalRule resource.
func (r *InspectionGlobalRuleResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(PROVIDER_NAME + "_" + r.resourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an Inspection Global Rule. It defines for each Situation elements/Situation categories an inspection reaction.",
		Attributes:  GetInspectionGlobalRuleSchemaAttributes(ctx),
		Blocks:      GetInspectionGlobalRuleSchemaBlocks(ctx),
	} // schema

}

// NewInspectionGlobalRuleResource creates a new instance of the InspectionGlobalRule resource.
func NewInspectionGlobalRuleResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing InspectionGlobalRule resource")
	r := &InspectionGlobalRuleResource{
		ResourceBase: ResourceBase[InspectionGlobalRuleResourceModel]{
			resourceType:  "inspection_global_rule",
			isSubResource: true,
		},
	}
	r.ResourceBase.dispatch = r
	return r
}

// special case for rank attribute
func (r *InspectionGlobalRuleResource) getCreateRequestParams(_ context.Context, data *InspectionGlobalRuleResourceModel) (map[string]string, error) {
	if !data.Rank.IsNull() && !data.Rank.IsUnknown() {
		queryParams := map[string]string{
			"keep_specified_rank": "true",
		}
		return queryParams, nil
	}
	return nil, nil
}
