// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Custom_Properties_Profile
// Package provider implements the SMC Terraform provider resources and data sources.
package provider





import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)


// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &CustomPropertiesProfileResource{}
var _ resource.ResourceWithImportState = &CustomPropertiesProfileResource{}
var _ context.Context = context.Background()


// CustomPropertiesProfileResource defines the resource implementation.
type CustomPropertiesProfileResource struct {
    ResourceBase[CustomPropertiesProfileResourceModel]
}


// Schema defines the schema for the CustomPropertiesProfile resource.
func (r *CustomPropertiesProfileResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
      Description: "This represents a Custom Properties Profile Element, which allows users to define custom properties and scripts for dynamic elements.",
      Attributes: GetCustomPropertiesProfileSchemaAttributes(ctx),
      Blocks: GetCustomPropertiesProfileSchemaBlocks(ctx),
    } // schema
    

}

// NewCustomPropertiesProfileResource creates a new instance of the CustomPropertiesProfile resource.
func NewCustomPropertiesProfileResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing CustomPropertiesProfile resource")
	r := &CustomPropertiesProfileResource{
        ResourceBase: ResourceBase[CustomPropertiesProfileResourceModel]{
             resourceType: "custom_properties_profile",
             isSubResource: false,

        },
    }
    r.ResourceBase.dispatch = r
    return r
}