// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetStaticMulticastRouteSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "dest_interface": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "The destination interfaces for the multicast route specified by their interface IDs. This is a collection of interface IDs that the multicast traffic will be routed to.",
         ElementType: types.StringType,
       },
       "dest_ip": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The destination IP address for the multicast route.",
        },
       "source_interface": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The source interface ID for the multicast route.",
        },
       "source_ip": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The source IP address for the multicast route.",
        },

    }
}
func GetStaticMulticastRouteSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{

    }
}