// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetAbstractProtocolAgentParameterSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {

    }
}
func GetAbstractProtocolAgentParameterSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{
       "pa_parameter": schema.SingleNestedBlock{
        Description: "This represents a parameter for the Protocol Agent, allowing for detailed configuration of agent settings.",
        CustomType:  customfield.NewNestedObjectType[PaParameterResourceModel](ctx),
        Attributes: GetPaParameterSchemaAttributes(ctx),Blocks: GetPaParameterSchemaBlocks(ctx),},
       "pa_parameter_group": schema.SingleNestedBlock{
        Description: "This represents a group of parameters for the Protocol Agent, allowing for structured configuration of agent settings.",
        CustomType:  customfield.NewNestedObjectType[PaParameterGroupResourceModel](ctx),
        Attributes: GetPaParameterGroupSchemaAttributes(ctx),Blocks: GetPaParameterGroupSchemaBlocks(ctx),},

    }
}