// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetOspfv2AreaSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
        "id": schema.StringAttribute{
        Optional:            true,
        Computed:            true,
        Description: "this attribute is the identifier of terraform resource",
        
        },
       "admin_domain": schema.StringAttribute {
        Computed: true,
       Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
        },
       "area_default_cost": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The default cost for this OSPF area. This is used to determine the cost of routes in this area. If the area type is 'normal', this value is not applicable and should be null.",
       },
       "area_id": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The unique identifier for the OSPF area.",
       },
       "area_type": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The type of the OSPF area.",
        },
       "comment": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "An optional comment for the element. This field is not required.",
        },
       "etag": schema.StringAttribute {
        Computed: true,
       Description: "The ETag of the element, used for versioning. This field is not required.",
        },
       "inbound_filters_ref": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the inbound filter access list.",
         ElementType: types.StringType,
       },
       "interface_settings_ref": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents the abstract OSPF Interface Settings used as Dynamic Routing element. It contains settings related to OSPF interface configuration.",
        },
       "key": schema.Int64Attribute {
          Computed: true,
         Description: "The unique identifier for the element. This field is required for updates but not for creation.",
       },
       "link": schema.ListNestedAttribute {
          Computed: true,
         Description: "The API's links of the element, providing additional actions or resources.",
         CustomType:  customfield.NewNestedObjectListType[ApiLinkResourceModel](ctx),
         NestedObject: schema.NestedAttributeObject{
         Attributes: GetApiLinkSchemaAttributes(ctx),
          },
         },
       "lk": schema.MapAttribute {
          Computed: true,
         Description: "",
  	ElementType: types.StringType,
      CustomType:  customfield.NewMapType[types.String](ctx),

       },
       "locked": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is locked. This field is not required.",
       },
       "name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "Name of the object.",
        },
       "outbound_filters_ref": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the outbound filter access list.",
         ElementType: types.StringType,
       },
       "read_only": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is read-only. This field is not required.",
       },
       "shortcut_capable_area": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether this OSPF area is capable of shortcut routing.",
       },
       "system": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is a System element. This field is not required.",
       },
       "system_key": schema.Int64Attribute {
          Computed: true,
         Description: "The system key of the System element. This field is not required.",
       },
       "trashed": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is trashed. This field is not required.",
       },

    }
}
func GetOspfv2AreaSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{
       "ospf_abr_substitute_container": schema.ListNestedBlock {
         NestedObject: schema.NestedBlockObject{
         Attributes: GetOspfAbrSubstituteContainerSchemaAttributes(ctx),
         Blocks: GetOspfAbrSubstituteContainerSchemaBlocks(ctx),
          },
         },
       "ospfv2_virtual_links_endpoints_container": schema.ListNestedBlock {
         NestedObject: schema.NestedBlockObject{
         Attributes: GetOspfv2VirtualLinksEndPointsContainerSchemaAttributes(ctx),
         Blocks: GetOspfv2VirtualLinksEndPointsContainerSchemaBlocks(ctx),
          },
         },

    }
}