// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetLinkUsageProfileSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
        "id": schema.StringAttribute{
        Optional:            true,
        Computed:            true,
        Description: "this attribute is the identifier of terraform resource",
        
        },
       "admin_domain": schema.StringAttribute {
        Computed: true,
       Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
        },
       "comment": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "An optional comment for the element. This field is not required.",
        },
       "default_link_balancing_preference": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The Default SD-WAN Link balancing preference. This is a value comprised between 0 and 4. Default value is 0 and means Equal Balancing.",
       },
       "etag": schema.StringAttribute {
        Computed: true,
       Description: "The ETag of the element, used for versioning. This field is not required.",
        },
       "key": schema.Int64Attribute {
          Computed: true,
         Description: "The unique identifier for the element. This field is required for updates but not for creation.",
       },
       "link": schema.ListNestedAttribute {
          Computed: true,
         Description: "The API's links of the element, providing additional actions or resources.",
         CustomType:  customfield.NewNestedObjectListType[ApiLinkResourceModel](ctx),
         NestedObject: schema.NestedAttributeObject{
         Attributes: GetApiLinkSchemaAttributes(ctx),
          },
         },
       "link_dont_duplicate_link_type_ref": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the Link Type.",
         ElementType: types.StringType,
       },
       "link_duplicate_qos_ref": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the QoS Class.",
         ElementType: types.StringType,
       },
       "link_fec_percentage": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "Forward Erasure Correction percentage indicating the ratio of correction packets to data packets.",
       },
       "link_fec_qos_ref": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the QoS Class.",
         ElementType: types.StringType,
       },
       "link_fec_threshold": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "Packet drop threshold that will start Forward Erasure Correction. This is a value comprised between 0 and 100.",
       },
       "link_fec_type_ref": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the Link Type.",
         ElementType: types.StringType,
       },
       "lk": schema.MapAttribute {
          Computed: true,
         Description: "",
  	ElementType: types.StringType,
      CustomType:  customfield.NewMapType[types.String](ctx),

       },
       "locked": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is locked. This field is not required.",
       },
       "name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "Name of the object.",
        },
       "read_only": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is read-only. This field is not required.",
       },
       "system": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is a System element. This field is not required.",
       },
       "system_key": schema.Int64Attribute {
          Computed: true,
         Description: "The system key of the System element. This field is not required.",
       },
       "trashed": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is trashed. This field is not required.",
       },

    }
}
func GetLinkUsageProfileSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{
       "link_usage_exception": schema.ListNestedBlock {
         NestedObject: schema.NestedBlockObject{
         Attributes: GetLinkUsageEntrySchemaAttributes(ctx),
         Blocks: GetLinkUsageEntrySchemaBlocks(ctx),
          },
         },

    }
}