// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetDeleteLogTaskSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
        "id": schema.StringAttribute{
        Optional:            true,
        Computed:            true,
        Description: "this attribute is the identifier of terraform resource",
        
        },
       "admin_domain": schema.StringAttribute {
        Computed: true,
       Description: "This represents a Domain. Domains are administrative boundaries that allow you to separate the configuration details and other information in the system for the purpose of limiting administrator access.",
        },
       "comment": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "An optional comment for the element. This field is not required.",
        },
       "delete_source_data": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if after the archive operation, logs need to be deleted. If true, logs will be deleted after archiving.",
       },
       "end_time": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The end time in ms used when the time_limit_type is set to 'absolute_time_range'.",
       },
       "etag": schema.StringAttribute {
        Computed: true,
       Description: "The ETag of the element, used for versioning. This field is not required.",
        },
       "file_format": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The file format for the export/archive mode: 'csv' for CSV format, 'xml' for XML format, 'zip' for ZIP format, 'cef' for CEF format, 'leef' for LEEF format, 'esm' for ESM format, 'snoop' for IPS recordings as SNOOP, 'pcap' for IPS recordings as PCAP, 'ips_raw_recordings' for IPS recordings as RAW.",
        },
       "file_name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The path where the archive/export will be stored.",
        },
       "filter_for_delete": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents a Filter Expression Container, which is a top-level re-usable filter that contains filter expression nodes.",
        },
       "filter_for_export": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents a Filter Expression Container, which is a top-level re-usable filter that contains filter expression nodes.",
        },
       "for_alert_event_log": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if Alert event logs need to be considered for the task.",
       },
       "for_alert_log": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if Alert logs need to be considered for the task.",
       },
       "for_audit_log": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if Audit logs need to be considered for the task.",
       },
       "for_fw_log": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if firewall logs need to be considered for the task.",
       },
       "for_ips_log": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if IPS logs need to be considered for the task.",
       },
       "for_ips_recording_log": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if IPS Recording logs need to be considered for the task.",
       },
       "for_l2fw_log": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if L2FW logs need to be considered for the task.",
       },
       "for_third_party_log": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if Third Party logs need to be considered for the task.",
       },
       "ips_recordings": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "Optional IPS record IDs for PCAP/SNOOP/RAW IPS recording export logs.",
         ElementType: types.Int64Type,
       },
       "is_local_location": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Flag to know if the archive/export file will be stored on the log server (false) or locally (true).",
       },
       "key": schema.Int64Attribute {
          Computed: true,
         Description: "The unique identifier for the element. This field is required for updates but not for creation.",
       },
       "link": schema.ListNestedAttribute {
          Computed: true,
         Description: "The API's links of the element, providing additional actions or resources.",
         CustomType:  customfield.NewNestedObjectListType[ApiLinkResourceModel](ctx),
         NestedObject: schema.NestedAttributeObject{
         Attributes: GetApiLinkSchemaAttributes(ctx),
          },
         },
       "lk": schema.MapAttribute {
          Computed: true,
         Description: "",
  	ElementType: types.StringType,
      CustomType:  customfield.NewMapType[types.String](ctx),

       },
       "locked": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is locked. This field is not required.",
       },
       "name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "Name of the object.",
        },
       "overwrite_file_flag": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The overwrite options: 'append' for append option, 'overwrite' for overwrite option, 'use_number_in_file_name' for creating a unique file with number as name, 'fail_task' for failing the task.",
        },
       "read_only": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is read-only. This field is not required.",
       },
       "relative_time_begin": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The begin number of days when the time_limit_type is set to 'relative_time_range' or 'before'.",
       },
       "relative_time_end": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The end number of days when the time_limit_type is set to 'relative_time_range' or 'before'.",
       },
       "resources": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the resource.",
         ElementType: types.StringType,
       },
       "script_name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The script to execute after the task.",
        },
       "start_time": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The start time in ms used when the time_limit_type is set to 'absolute_time_range' or 'after'.",
       },
       "system": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is a System element. This field is not required.",
       },
       "system_key": schema.Int64Attribute {
          Computed: true,
         Description: "The system key of the System element. This field is not required.",
       },
       "time_limit_type": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "Log task time limit type: Time range type. 'before' for 'relative_time_end' number of days, 'relative_time_range' for between 'relative_time_begin' number of days and 'relative_time_end' number of days, 'absolute_time_range' for between 'start_time' time in ms and 'end_time' time in ms. 'today' for today. 'yesterday' for yesterday. 'last_full_week_sun_sat' for last full week (sunday-saturday). 'last_full_week_mon_sun' for last full week (monday-sunday). 'last_full_month' for last full month. 'after' for after 'start_time' time in ms.",
        },
       "trashed": schema.BoolAttribute {
          Computed: true,
         Description: "Indicates if the element is trashed. This field is not required.",
       },

    }
}
func GetDeleteLogTaskSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{
       "server_directories": schema.ListNestedBlock {
         NestedObject: schema.NestedBlockObject{
         Attributes: GetServerDirectoriesSchemaAttributes(ctx),
         Blocks: GetServerDirectoriesSchemaBlocks(ctx),
          },
         },

    }
}