// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetSandboxSettingsSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "http_proxy": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the HTTP Proxy.",
         ElementType: types.StringType,
       },
       "sandbox_license_key": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The license key for the sandbox service, which is required for activation and usage of the sandbox features.",
        },
       "sandbox_license_token": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The license token for the sandbox service, which is used for authentication and authorization of sandbox features.",
        },
       "sandbox_service": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents the Sandbox service element (referenced by sandbox settings). It contains information about the portal account, data center, license key and token.",
        },

    }
}
func GetSandboxSettingsSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{

    }
}