// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetCertificateSettingsSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "certificate_type": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The type of certificate to be used.",
        },
       "check_revocation": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether to check the revocation status of the certificate.",
       },
       "ignore_revocation_on_failure": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether to ignore revocation checks when an error occurs.",
       },
       "subject_alt_name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The subject alternative name (SAN) for the certificate, typically a DNS name.",
        },
       "subject_name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The distinguished name (DN) for the certificate.",
        },

    }
}
func GetCertificateSettingsSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{

    }
}