// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetCertificateValidationSettingsSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "crl_distribution_point_list": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "A list of URLs representing the distribution points to use for CRL (Certificate Revocation List) cache on the engine.",
         ElementType: types.StringType,
       },
       "http_proxy_ref": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents an HTTP Proxy, which is used to route HTTP traffic through a proxy server. It includes attributes for IP address, port, username, and password.",
        },
       "ocsp_crl_timeout": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The timeout in seconds for OCSP and CRL lookups. This setting determines how long the engine will wait for a response before timing out.",
       },

    }
}
func GetCertificateValidationSettingsSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{

    }
}