// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetVirtualFirewallNodeSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
        "id": schema.StringAttribute{
        Optional:            true,
        Computed:            true,
        Description: "this attribute is the identifier of terraform resource",
        
        },        
        "from_ref": schema.StringAttribute{
        Optional:            true, 
        Description: "parent href of this sub-resource",
        },
       "activate_test": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether test entries are activated on this engine node or not.",
       },
       "comment": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "An optional comment for the element. This field is not required.",
        },
       "engine_version": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The version of the software running on the engine node.",
        },
       "key": schema.Int64Attribute {
          Computed: true,
         Description: "The unique identifier for the element. This field is required for updates but not for creation.",
       },
       "link": schema.ListNestedAttribute {
          Computed: true,
         Description: "The API's links of the element, providing additional actions or resources.",
         CustomType:  customfield.NewNestedObjectListType[ApiLinkResourceModel](ctx),
         NestedObject: schema.NestedAttributeObject{
         Attributes: GetApiLinkSchemaAttributes(ctx),
          },
         },
       "lk": schema.MapAttribute {
          Computed: true,
         Description: "",
  	ElementType: types.StringType,
      CustomType:  customfield.NewMapType[types.String](ctx),

       },
       "name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "Name of the object.",
        },
       "nodeid": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The unique identifier of the engine node in the cluster, which is a value between 1 and 16.",
       },
       "snmp_engine_id": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The SNMP Engine ID for the engine node, which is used for SNMP communication. If not specified, it will be automatically generated.",
        },
       "snmp_location": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The SNMP location for the engine node, which provides information about the physical location of the node.",
        },

    }
}
func GetVirtualFirewallNodeSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{
       "appliance_info": schema.SingleNestedBlock{
        Description: "This represents the Appliance data for an engine Node, including product name, hardware version, initial contact time, first upload time, proof of serial, software version, software features, cloud identifiers, and remaining days before initial license expiration.",
        CustomType:  customfield.NewNestedObjectType[ApplianceInfoResourceModel](ctx),
        Attributes: GetApplianceInfoSchemaAttributes(ctx),Blocks: GetApplianceInfoSchemaBlocks(ctx),},
       "external_pki_certificate_settings": schema.SingleNestedBlock{
        Description: "This represents the certificate settings for an element, including the subject name, subject alt name, certificate type, and revocation check settings.",
        CustomType:  customfield.NewNestedObjectType[CertificateSettingsResourceModel](ctx),
        Attributes: GetCertificateSettingsSchemaAttributes(ctx),Blocks: GetCertificateSettingsSchemaBlocks(ctx),},
       "loopback_node_dedicated_interface": schema.ListNestedBlock {
         NestedObject: schema.NestedBlockObject{
         Attributes: GetLoopbackNodeInterfaceSchemaAttributes(ctx),
         Blocks: GetLoopbackNodeInterfaceSchemaBlocks(ctx),
          },
         },
       "tests": schema.ListNestedBlock {
         NestedObject: schema.NestedBlockObject{
         Attributes: GetTestEntryWrapperSchemaAttributes(ctx),
         Blocks: GetTestEntryWrapperSchemaBlocks(ctx),
          },
         },

    }
}