// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetDynamicRoutingSettingsSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "antispoofing_ne_ref": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the Network Element used for antispoofing.",
         ElementType: types.StringType,
       },
       "path_count": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The path count for equal cost multi-path routing, which determines the number of paths used for routing decisions.",
       },

    }
}
func GetDynamicRoutingSettingsSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{
       "bgp": schema.SingleNestedBlock{
        Description: "This represents the BGP Dynamic Routing Firewall Settings, including BGP Profile, Router ID, and Autonomous System.",
        CustomType:  customfield.NewNestedObjectType[BgpSettingsResourceModel](ctx),
        Attributes: GetBgpSettingsSchemaAttributes(ctx),Blocks: GetBgpSettingsSchemaBlocks(ctx),},
       "ospfv2": schema.SingleNestedBlock{
        Description: "This represents the OSPFv2 Dynamic Routing settings for the firewall, including whether it is enabled, the router ID, and the associated OSPFv2 profile.",
        CustomType:  customfield.NewNestedObjectType[Ospfv2SettingsResourceModel](ctx),
        Attributes: GetOspfv2SettingsSchemaAttributes(ctx),Blocks: GetOspfv2SettingsSchemaBlocks(ctx),},

    }
}