// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetBgpBmpEntrySchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "bmp_address": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The BMP address value, which can be a FQDN, IPv4, or IPv6 address.",
        },
       "bmp_connect_through_master": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether the BMP connection is connected through the master.",
       },
       "bmp_port": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The BMP port value.",
       },
       "subnet": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents a network element, which is a component that has an IP address and can be part of a network. It includes a location reference.",
        },

    }
}
func GetBgpBmpEntrySchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{

    }
}