// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetExternalTestSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "alert_notification": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether an alert notification is sent if the test fails.",
       },
       "command_line": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The command line to execute the external test script. The script must return an exit code of 0 (zero) if it succeeds. Any non-zero return value is considered a failure. Caution: This test allows administrators who have permissions to edit the properties of Engines to run arbitrary commands in the Engine operating system.",
        },
       "comment": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "An optional comment for the element. This field is not required.",
        },
       "key": schema.Int64Attribute {
          Computed: true,
         Description: "The unique identifier for the element. This field is required for updates but not for creation.",
       },
       "link": schema.ListNestedAttribute {
          Computed: true,
         Description: "The API's links of the element, providing additional actions or resources.",
         CustomType:  customfield.NewNestedObjectListType[ApiLinkResourceModel](ctx),
         NestedObject: schema.NestedAttributeObject{
         Attributes: GetApiLinkSchemaAttributes(ctx),
          },
         },
       "lk": schema.MapAttribute {
          Computed: true,
         Description: "",
  	ElementType: types.StringType,
      CustomType:  customfield.NewMapType[types.String](ctx),

       },
       "name": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "Name of the object.",
        },
       "offline_state": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether the test is executed when the engine is offline or not.",
       },
       "online_state": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether the test is executed when the engine is online or not.",
       },
       "retry_count": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The number of times the test will be retried if it fails. Note! We recommend always setting the retry count to more than 1 to avoid creating overly sensitive tests that burden the system unnecessarily.",
       },
       "snmp_notification": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether an SNMP notification is sent if the test fails.",
       },
       "standby_state": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether the test is executed when the engine is in standby state or not.",
       },
       "test_action": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The action to be taken if the test fails. Options include 'none', 'offline', 'forceoffline', and 'forcespeed'.",
        },
       "test_active": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether the test is active or not.",
       },
       "test_interval": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The interval in seconds at which the test is executed. Note! Running a test too frequently can increase overhead.",
       },
       "test_timeout": schema.Int64Attribute {
         Optional: true, // todo optional parameters
         Description: "The timeout in milliseconds for the external test. If the test does not return a response within this time, it is considered to have failed. To avoid overly short timeout values. We recommend a timeout of 500 - 1000 ms depending on the external test script",
       },

    }
}
func GetExternalTestSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{

    }
}