// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetAliasValueSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "alias_ref": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents a network element, which is a component that has an IP address and can be part of a network. It includes a location reference.",
        },
       "cluster_ref": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents a group of devices, or nodes, that share a given work load. You can cluster Firewalls, IPS engines, and Layer 2 Firewalls to share the load and provide redundancy, allowing, for example, scheduled maintenance that takes one node out of service without interrupting services to the users.",
        },
       "resolved_value": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "The resolved values for the Alias, which are the actual values used in the policies.",
         ElementType: types.StringType,
       },
       "translated_element": schema.ListAttribute {
         Optional: true, // todo optional parameters
         Description: "URI of the Network Element used as translated element.",
         ElementType: types.StringType,
       },

    }
}
func GetAliasValueSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{

    }
}